const EXAMPLES_B = [
  ["他开车去公司。","Tā kāichē qù gōngsī.","He drives to the company."],
  ["坐车要三十分钟。","Zuòchē yào sānshí fēnzhōng.","The ride takes 30 minutes."],
  ["我在考驾照。","Wǒ zài kǎo jiàzhào.","I'm taking my driving test."],
  ["骑摩托车要戴安全帽。","Qí mótuōchē yào dài ānquánmào.","Wear a helmet when riding a motorbike."],
  ["妈妈让我把晚饭送过去。","Māma ràng wǒ bǎ wǎnfàn sòng guòqu.","Mom asked me to take the dinner over."],
  ["我妈妈很会做菜。","Wǒ māma hěn huì zuòcài.","My mom is great at cooking."],
  ["这里有很多美食。","Zhèlǐ yǒu hěn duō měishí.","There's lots of great food here."],
  ["冬天最适合吃火锅。","Dōngtiān zuì shìhé chī huǒguō.","Hotpot is best in winter."],
  ["先煮汤。","Xiān zhǔ tāng.","First boil the soup."],
  ["我会炒鸡蛋。","Wǒ huì chǎo jīdàn.","I can stir-fry eggs."],
  ["我喜欢吃煎鸡蛋。","Wǒ xǐhuan chī jiān jīdàn.","I like fried eggs."],
  ["蒸鱼很好吃。","Zhēng yú hěn hǎochī.","Steamed fish is delicious."],
  ["我喜欢吃烤鸭。","Wǒ xǐhuan chī kǎoyā.","I like roast duck."],
  ["把菜放在锅里。","Bǎ cài fàng zài guō lǐ.","Put the food in the pot."],
  ["给我一个碗。","Gěi wǒ yí ge wǎn.","Give me a bowl."],
  ["我不会用筷子。","Wǒ bú huì yòng kuàizi.","I can't use chopsticks."],
  ["我喜欢吃鱼。","Wǒ xǐhuan chī yú.","I like eating fish."],
  ["早上我吃了一个鸡蛋。","Zǎoshang wǒ chī le yí ge jīdàn.","I ate an egg this morning."],
  ["这是牛肉面。","Zhè shì niúròu miàn.","This is beef noodle soup."],
  ["放一点酱油。","Fàng yìdiǎn jiàngyóu.","Add a little soy sauce."],
  ["菜里放点盐。","Cài lǐ fàng diǎn yán.","Add some salt to the dish."],
  ["我的咖啡不放糖。","Wǒ de kāfēi bú fàng táng.","I don't put sugar in my coffee."],
  ["我怕辣椒。","Wǒ pà làjiāo.","I can't handle chili."],
  ["这个菜有点辣。","Zhège cài yǒudiǎn là.","This dish is a bit spicy."],
  ["这个蛋糕很甜。","Zhège dàngāo hěn tián.","This cake is very sweet."],
  ["这个草莓有点酸。","Zhège cǎoméi yǒudiǎn suān.","This strawberry is a bit sour."],
  ["我不喜欢洋葱。","Wǒ bù xǐhuan yángcōng.","I don't like onions."],
  ["汤里放点姜。","Tāng lǐ fàng diǎn jiāng.","Add some ginger to the soup."],
  ["我喜欢吃奶酪。","Wǒ xǐhuan chī nǎilào.","I like cheese."],
  ["虽然很累，但是很开心。","Suīrán hěn lèi, dànshì hěn kāixīn.","Although tired, I'm happy."],
  ["红色很漂亮，不过我更喜欢黑色。","Hóngsè hěn piàoliang, búguò wǒ gèng xǐhuan hēisè.","Red is pretty, but I prefer black."],
  ["房子很新，而且家具都有。","Fángzi hěn xīn, érqiě jiāju dōu yǒu.","The house is new, and it's fully furnished."],
  ["我们差不多到了。","Wǒmen chàbùduō dào le.","We're almost there."],
  ["大概二十分钟。","Dàgài èrshí fēnzhōng.","About twenty minutes."],
  ["我一般八点起床。","Wǒ yìbān bā diǎn qǐchuáng.","I usually get up at eight."],
  ["你最近怎么样？","Nǐ zuìjìn zěnmeyàng?","How have you been lately?"],
  ["先吃饭，然后休息。","Xiān chīfàn, ránhòu xiūxi.","Eat first, then rest."],
  ["我们一起去吧。","Wǒmen yìqǐ qù ba.","Let's go together."],
  ["他可能不来了。","Tā kěnéng bù lái le.","He might not come."],
  ["我觉得这里很好。","Wǒ juéde zhèlǐ hěn hǎo.","I think it's nice here."],
  ["你需要帮助吗？","Nǐ xūyào bāngzhù ma?","Do you need help?"],
  ["我决定住在这里。","Wǒ juédìng zhù zài zhèlǐ.","I've decided to live here."],
  ["我一点儿也不累。","Wǒ yìdiǎnr yě bù lèi.","I'm not tired at all."],
  ["我不得不工作。","Wǒ bùdébù gōngzuò.","I have to work."],
  ["清迈的大自然很美丽。","Qīngmài de dàzìrán hěn měilì.","Chiang Mai's nature is beautiful."],
  ["我慢慢接受了新的生活。","Wǒ mànmàn jiēshòu le xīn de shēnghuó.","I gradually accepted the new life."],
  ["今天我穿了一件外套。","Jīntiān wǒ chuān le yí jiàn wàitào.","Today I'm wearing a coat."],
  ["她戴着一条项链。","Tā dài zhe yì tiáo xiàngliàn.","She's wearing a necklace."],
  ["学生常常背着书包。","Xuésheng chángcháng bēi zhe shūbāo.","Students often carry a backpack."],
  ["他戴着一顶帽子。","Tā dài zhe yì dǐng màozi.","He's wearing a hat."],
  ["冬天我喜欢戴围巾。","Dōngtiān wǒ xǐhuan dài wéijīn.","In winter I like wearing a scarf."],
  ["他今天打了领带。","Tā jīntiān dǎ le lǐngdài.","He wore a tie today."],
  ["这条皮带是黑色的。","Zhè tiáo pídài shì hēisè de.","This belt is black."],
  ["这条项链很漂亮。","Zhè tiáo xiàngliàn hěn piàoliang.","This necklace is beautiful."],
  ["她手上有一个戒指。","Tā shǒu shàng yǒu yí ge jièzhi.","She has a ring on her hand."],
  ["她戴着新耳环。","Tā dài zhe xīn ěrhuán.","She's wearing new earrings."],
  ["这个手表很贵。","Zhège shǒubiǎo hěn guì.","This watch is expensive."],
  ["我每天戴眼镜。","Wǒ měitiān dài yǎnjìng.","I wear glasses every day."],
  ["我买了一双袜子。","Wǒ mǎi le yì shuāng wàzi.","I bought a pair of socks."],
  ["今天很冷，穿上外套。","Jīntiān hěn lěng, chuān shàng wàitào.","It's cold today, put on a coat."],
  ["你的包是什么颜色的？","Nǐ de bāo shì shénme yánsè de?","What color is your bag?"],
  ["她拿着一个大袋子。","Tā ná zhe yí ge dà dàizi.","She's carrying a big bag."],
  ["她喜欢买首饰。","Tā xǐhuan mǎi shǒushì.","She likes buying jewelry."],
  ["她今天打扮得很漂亮。","Tā jīntiān dǎban de hěn piàoliang.","She's dressed up beautifully today."],
  ["用刀把牛肉切片。","Yòng dāo bǎ niúròu qiē piàn.","Use a knife to slice the beef."],
  ["桌子上有一个盘子。","Zhuōzi shàng yǒu yí ge pánzi.","There's a plate on the table."],
  ["给我一个勺子。","Gěi wǒ yí ge sháozi.","Give me a spoon."],
  ["用微波炉热一下饭。","Yòng wēibōlú rè yíxià fàn.","Heat the rice in the microwave."],
  ["蛋糕在烤箱里。","Dàngāo zài kǎoxiāng lǐ.","The cake is in the oven."],
  ["请把菜放在菜板上。","Qǐng bǎ cài fàng zài càibǎn shàng.","Put the vegetables on the cutting board."],
  ["我喜欢吃虾。","Wǒ xǐhuan chī xiā.","I like eating shrimp."],
  ["饺子要放点醋。","Jiǎozi yào fàng diǎn cù.","Add some vinegar to the dumplings."],
  ["汤里放点胡椒粉。","Tāng lǐ fàng diǎn hújiāofěn.","Add some pepper to the soup."],
  ["炒菜要放蒜。","Chǎocài yào fàng suàn.","Add garlic when stir-frying."],
  ["火锅里放点白菜。","Huǒguō lǐ fàng diǎn báicài.","Add some cabbage to the hotpot."],
  ["我早饭吃了香肠。","Wǒ zǎofàn chī le xiāngcháng.","I had sausage for breakfast."],
  ["我们拌一个沙拉。","Wǒmen bàn yí ge shālā.","Let's toss a salad."],
  ["妈妈在炖牛肉。","Māma zài dùn niúròu.","Mom is stewing beef."],
  ["我不喜欢吃炸的东西。","Wǒ bù xǐhuan chī zhá de dōngxi.","I don't like fried food."],
  ["我喜欢吃清淡的菜。","Wǒ xǐhuan chī qīngdàn de cài.","I like light-flavored food."],
  ["这个菜有点油腻。","Zhège cài yǒudiǎn yóunì.","This dish is a bit greasy."],
  ["你放了什么调料？","Nǐ fàng le shénme tiáoliào?","What seasonings did you add?"],
  ["我买了一张机票。","Wǒ mǎi le yì zhāng jīpiào.","I bought a plane ticket."],
  ["火车站离这儿不远。","Huǒchēzhàn lí zhèr bù yuǎn.","The train station isn't far from here."],
  ["地铁站就在楼下。","Dìtiězhàn jiù zài lóu xià.","The subway station is right downstairs."],
  ["车上有很多乘客。","Chē shàng yǒu hěn duō chéngkè.","There are many passengers on board."],
  ["我的航班晚点了。","Wǒ de hángbān wǎndiǎn le.","My flight is delayed."],
  ["头等舱很贵。","Tóuděngcāng hěn guì.","First class is expensive."],
  ["我坐经济舱。","Wǒ zuò jīngjìcāng.","I fly economy class."],
  ["我们现在开始登机。","Wǒmen xiànzài kāishǐ dēngjī.","We're now boarding."],
  ["他有一辆私家车。","Tā yǒu yí liàng sījiāchē.","He has a private car."],
  ["我坐长途汽车去别的城市。","Wǒ zuò chángtú qìchē qù bié de chéngshì.","I take a coach to another city."],
  ["这是这趟车的始发站。","Zhè shì zhè tàng chē de shǐfāzhàn.","This is the departure station for this train."],
  ["下一站是终点站。","Xià yí zhàn shì zhōngdiǎnzhàn.","The next stop is the last stop."],
  ["我买了往返机票。","Wǒ mǎi le wǎngfǎn jīpiào.","I bought a round-trip ticket."],
  ["我只要单程票。","Wǒ zhǐ yào dānchéng piào.","I only want a one-way ticket."],
  ["很多人骑电动车。","Hěn duō rén qí diàndòngchē.","Many people ride electric scooters."],
  ["请把灯打开。","Qǐng bǎ dēng dǎkāi.","Please turn on the light."],
  ["窗户开着。","Chuānghu kāi zhe.","The window is open."],
  ["天气很热，开空调吧。","Tiānqì hěn rè, kāi kōngtiáo ba.","It's hot, let's turn on the AC."],
  ["他在看电视。","Tā zài kàn diànshì.","He's watching TV."],
  ["客厅里有一个沙发。","Kètīng lǐ yǒu yí ge shāfā.","There's a sofa in the living room."],
  ["卧室里有一张床。","Wòshì lǐ yǒu yì zhāng chuáng.","There's a bed in the bedroom."],
  ["房间里有两把椅子。","Fángjiān lǐ yǒu liǎng bǎ yǐzi.","There are two chairs in the room."],
  ["书柜上有很多书。","Shūguì shàng yǒu hěn duō shū.","There are many books on the bookcase."],
  ["衣服都在衣柜里。","Yīfu dōu zài yīguì lǐ.","The clothes are all in the wardrobe."],
  ["水果在冰箱里。","Shuǐguǒ zài bīngxiāng lǐ.","The fruit is in the fridge."],
  ["夏天我用电风扇。","Xiàtiān wǒ yòng diànfēngshàn.","I use a fan in summer."],
  ["墙上挂着一幅画。","Qiáng shàng guà zhe yì fú huà.","There's a painting on the wall."],
  ["地上有一块地毯。","Dì shàng yǒu yí kuài dìtǎn.","There's a rug on the floor."],
  ["我想换窗帘的颜色。","Wǒ xiǎng huàn chuānglián de yánsè.","I want to change the curtain color."],
  ["墙上有一个钟。","Qiáng shàng yǒu yí ge zhōng.","There's a clock on the wall."],
  ["我把照片挂在墙上。","Wǒ bǎ zhàopiàn guà zài qiáng shàng.","I hung the photo on the wall."],
  ["把书放在桌子上。","Bǎ shū fàng zài zhuōzi shàng.","Put the book on the table."],
  ["桌子上摆着几个杯子。","Zhuōzi shàng bǎi zhe jǐ ge bēizi.","Several cups are placed on the table."],
  ["我每天早睡早起。","Wǒ měitiān zǎoshuì zǎoqǐ.","I go to bed early and get up early every day."],
  ["你不应该经常熬夜。","Nǐ bù yīnggāi jīngcháng áoyè.","You shouldn't stay up late so often."],
  ["我朋友是一个夜猫子。","Wǒ péngyou shì yí ge yèmāozi.","My friend is a night owl."],
  ["我的作息时间很健康。","Wǒ de zuòxī shíjiān hěn jiànkāng.","My daily routine is healthy."],
  ["我们要按时上学。","Wǒmen yào ànshí shàngxué.","We need to get to school on time."],
  ["我喜欢口味清淡的菜。","Wǒ xǐhuan kǒuwèi qīngdàn de cài.","I like food that's light in taste."],
  ["他口味很重，喜欢吃咸的。","Tā kǒuwèi hěn zhòng, xǐhuan chī xián de.","His taste is strong; he likes salty food."],
  ["每顿饭我只吃八成饱。","Měi dùn fàn wǒ zhǐ chī bāchéng bǎo.","I only eat until 80% full at every meal."],
  ["我每天早上喝茶或者咖啡。","Wǒ měitiān zǎoshang hē chá huòzhě kāfēi.","I drink tea or coffee every morning."],
  ["上课以前我会预习。","Shàngkè yǐqián wǒ huì yùxí.","I preview before class."],
  ["我们九点上课。","Wǒmen jiǔ diǎn shàngkè.","We go to class at nine."],
  ["我每天晚上做作业。","Wǒ měitiān wǎnshang zuò zuòyè.","I do homework every night."],
  ["我爸爸周末也要加班。","Wǒ bàba zhōumò yě yào jiābān.","My dad has to work overtime on weekends too."],
  ["我不吃肉，我是素食主义者。","Wǒ bù chī ròu, wǒ shì sùshí zhǔyìzhě.","I don't eat meat, I'm a vegetarian."],
  ["我不是不想去，而是没有时间。","Wǒ bú shì bù xiǎng qù, ér shì méiyǒu shíjiān.","It's not that I don't want to go, but I don't have time."],
  ["他戴着一副眼镜。","Tā dàizhe yí fù yǎnjìng.","He is wearing a pair of glasses."],
  ["吃了药以后，我好起来了。","Chīle yào yǐhòu, wǒ hǎo qǐlái le.","After taking the medicine, I started to feel better."],
  ["你可以带我去那家餐厅吗？","Nǐ kěyǐ dài wǒ qù nà jiā cāntīng ma?","Can you take me to that restaurant?"],
  ["我们明天去不去爬山，看情况。","Wǒmen míngtiān qù bu qù páshān, kàn qíngkuàng.","Whether we go hiking tomorrow depends on the situation."],
  ["我迟到了，真不好意思。","Wǒ chídào le, zhēn bù hǎoyìsi.","I'm late, I'm really sorry."],
  ["你还记得我的名字吗？","Nǐ hái jìde wǒ de míngzi ma?","Do you still remember my name?"],
  ["他今天上课迟到了。","Tā jīntiān shàngkè chídào le.","He was late for class today."],
  ["路上堵车，我们晚了半个小时。","Lùshàng dǔchē, wǒmen wǎn le bàn ge xiǎoshí.","There was a traffic jam, so we were half an hour late."],
  ["我每天七点起床。","Wǒ měitiān qī diǎn qǐchuáng.","I get up at seven every day."],
  ["你又迟到了！","Nǐ yòu chídào le!","You're late again!"],
  ["我每天早上跑步。","Wǒ měitiān zǎoshang pǎobù.","I go jogging every morning."],
  ["她最近在减肥。","Tā zuìjìn zài jiǎnféi.","She's been dieting recently."],
  ["我们这个星期五有考试。","Wǒmen zhège xīngqīwǔ yǒu kǎoshì.","We have an exam this Friday."],
  ["他不是普通人，而是一个很有名的画家。","Tā bú shì pǔtōngrén, ér shì yí ge hěn yǒumíng de huàjiā.","He's not an ordinary person, but a very famous painter."],
  ["我妈妈是一个画家。","Wǒ māma shì yí ge huàjiā.","My mom is a painter."],
  ["这家餐厅很有名。","Zhè jiā cāntīng hěn yǒumíng.","This restaurant is very famous."],
  ["对我来说，健康最重要。","Duì wǒ láishuō, jiànkāng zuì zhòngyào.","As far as I'm concerned, health is most important."],
  ["我的家乡是一个小镇。","Wǒ de jiāxiāng shì yí ge xiǎozhèn.","My hometown is a small town."],
  ["我住在北京的市区。","Wǒ zhù zài Běijīng de shìqū.","I live in downtown Beijing."],
  ["他从小在郊区长大。","Tā cóngxiǎo zài jiāoqū zhǎngdà.","He grew up in the suburbs."],
  ["我奶奶住在农村。","Wǒ nǎinai zhù zài nóngcūn.","My grandma lives in the countryside."],
  ["这个小镇只有几万人口。","Zhège xiǎozhèn zhǐ yǒu jǐ wàn rénkǒu.","This small town only has tens of thousands of people."],
  ["住在大城市有很多优点。","Zhù zài dà chéngshì yǒu hěn duō yōudiǎn.","Living in a big city has many advantages."],
  ["小镇的缺点是工作机会少。","Xiǎozhèn de quēdiǎn shì gōngzuò jīhuì shǎo.","The disadvantage of a small town is fewer job opportunities."],
  ["大城市有很多机会。","Dà chéngshì yǒu hěn duō jīhuì.","Big cities have many opportunities."],
  ["大城市的物价更高。","Dà chéngshì de wùjià gèng gāo.","Prices are higher in big cities."],
  ["大城市的空气质量不太好。","Dà chéngshì de kōngqì zhìliàng bú tài hǎo.","The air quality in big cities isn't very good."],
  ["小镇的工资不高。","Xiǎozhèn de gōngzī bù gāo.","Salaries in small towns aren't high."],
  ["小镇的生活很单纯。","Xiǎozhèn de shēnghuó hěn dānchún.","Life in a small town is very simple."],
  ["西安有很多历史建筑。","Xī'ān yǒu hěn duō lìshǐ jiànzhù.","Xi'an has many historical buildings."],
  ["北京有很多商业中心。","Běijīng yǒu hěn duō shāngyè zhōngxīn.","Beijing has many business centers."],
  ["周末我喜欢去逛街。","Zhōumò wǒ xǐhuan qù guàngjiē.","I like to go shopping on weekends."],
  ["市区有很多高楼。","Shìqū yǒu hěn duō gāolóu.","There are many tall buildings downtown."],
  ["北京有很多古老的胡同。","Běijīng yǒu hěn duō gǔlǎo de hútòng.","Beijing has many old hutongs."],
  ["我的家乡有很多四合院。","Wǒ de jiāxiāng yǒu hěn duō sìhéyuàn.","My hometown has many courtyard houses."],
  ["我在一个小镇长大。","Wǒ zài yí ge xiǎozhèn zhǎngdà.","I grew up in a small town."],
  ["郊区的空气比较新鲜。","Jiāoqū de kōngqì bǐjiào xīnxiān.","The air in the suburbs is relatively fresh."],
  ["农村的空气很新鲜。","Nóngcūn de kōngqì hěn xīnxiān.","The air in the countryside is very fresh."],
  ["从郊区到市区有高速公路。","Cóng jiāoqū dào shìqū yǒu gāosù gōnglù.","There's a highway from the suburbs to downtown."],
  ["开车去郊区要花一个小时。","Kāichē qù jiāoqū yào huā yí ge xiǎoshí.","It takes an hour to drive to the suburbs."],
  ["虽然有点远，但是很值得。","Suīrán yǒudiǎn yuǎn, dànshì hěn zhídé.","Although it's a bit far, it's worth it."],
  ["农村有很多树。","Nóngcūn yǒu hěn duō shù.","There are many trees in the countryside."],
  ["郊区有很多田野。","Jiāoqū yǒu hěn duō tiányě.","There are many fields in the suburbs."],
  ["我们坐船去了岛上。","Wǒmen zuò chuán qù le dǎo shàng.","We took a boat to the island."],
  ["小镇的生活很舒服。","Xiǎozhèn de shēnghuó hěn shūfu.","Life in a small town is comfortable."],
  ["我很想念我的家乡。","Wǒ hěn xiǎngniàn wǒ de jiāxiāng.","I miss my hometown a lot."],
  ["那是我最珍贵的记忆。","Nà shì wǒ zuì zhēnguì de jìyì.","That's my most precious memory."],
  ["家人是最珍贵的。","Jiārén shì zuì zhēnguì de.","Family is the most precious thing."],
  ["我永远不会忘记我的家乡。","Wǒ yǒngyuǎn bú huì wàngjì wǒ de jiāxiāng.","I will never forget my hometown."],
  ["这个城市有很大的变化。","Zhège chéngshì yǒu hěn dà de biànhuà.","This city has changed a lot."],
  ["我对这条路很熟悉。","Wǒ duì zhè tiáo lù hěn shúxī.","I'm very familiar with this road."],
  ["家乡的风景很美。","Jiāxiāng de fēngjǐng hěn měi.","The scenery in my hometown is beautiful."],
  ["回家的感觉很温暖。","Huí jiā de gǎnjué hěn wēnnuǎn.","The feeling of coming home is very warm."],
  ["到了新地方，你要入乡随俗。","Dàole xīn dìfang, nǐ yào rùxiāngsuísú.","When you arrive somewhere new, you should do as the locals do."],
  ["他或许不知道这件事。","Tā huòxǔ bù zhīdào zhè jiàn shì.","He perhaps doesn't know about this."],
  ["这里的天气很潮湿。","Zhèlǐ de tiānqì hěn cháoshī.","The weather here is very humid."],
  ["我要去超市买东西。","Wǒ yào qù chāoshì mǎi dōngxi.","I need to go to the supermarket to buy things."],
  ["我渐渐习惯了这里的生活。","Wǒ jiànjiàn xíguàn le zhèlǐ de shēnghuó.","I've gradually gotten used to life here."],
  ["我喜欢很多水果，比如苹果和香蕉。","Wǒ xǐhuan hěn duō shuǐguǒ, bǐrú píngguǒ hé xiāngjiāo.","I like a lot of fruits, for example apples and bananas."],
  ["他是个夜猫子，喜欢晚睡晚起。","Tā shì ge yèmāozi, xǐhuan wǎn shuì wǎn qǐ.","He's a night owl who likes to sleep late and rise late."],
  ["请进！","Qǐng jìn!","Please come in!"],
  ["学生们都在教室里。","Xuéshengmen dōu zài jiàoshì lǐ.","The students are all in the classroom."],
  ["大家好！","Dàjiā hǎo!","Hello everyone!"],
  ["为了不迟到，我很早就出门了。","Wèile bù chídào, wǒ hěn zǎo jiù chūmén le.","In order not to be late, I left very early."],
  ["我买了一个闹钟。","Wǒ mǎi le yí ge nàozhōng.","I bought an alarm clock."],
  ["我的闹钟坏了。","Wǒ de nàozhōng huài le.","My alarm clock is broken."],
  ["快起床，懒虫！","Kuài qǐchuáng, lǎnchóng!","Get up quickly, lazybones!"],
  ["你该起床了。","Nǐ gāi qǐchuáng le.","You should get up."],
  ["尽管很难，但是我还是要试试。","Jǐnguǎn hěn nán, dànshì wǒ háishi yào shìshi.","Although it's hard, I'll still give it a try."],
  ["谢谢你，我很感谢你的帮助。","Xièxie nǐ, wǒ hěn gǎnxiè nǐ de bāngzhù.","Thank you, I really appreciate your help."],
  ["我设置了一个中午的闹钟。","Wǒ shèzhì le yí ge zhōngwǔ de nàozhōng.","I set an alarm for noon."],
  ["我们中午一起吃饭吧。","Wǒmen zhōngwǔ yìqǐ chīfàn ba.","Let's eat together at noon."],
  ["你有时间吗？","Nǐ yǒu shíjiān ma?","Do you have time?"],
  ["有些人不喜欢喝咖啡。","Yǒuxiē rén bù xǐhuan hē kāfēi.","Some people don't like drinking coffee."],
  ["我们明天见面吧。","Wǒmen míngtiān jiànmiàn ba.","Let's meet tomorrow."],
  ["见到老师要问好。","Jiàndào lǎoshī yào wènhǎo.","You should say hello when you see the teacher."],
  ["这个问题很奇怪。","Zhège wèntí hěn qíguài.","This question is very strange."],
  ["我有一个问题。","Wǒ yǒu yí ge wèntí.","I have a question."],
  ["我的邻居很友好。","Wǒ de línjū hěn yǒuhǎo.","My neighbor is very friendly."],
  ["我们练习了一段对话。","Wǒmen liànxí le yí duàn duìhuà.","We practiced a dialogue."],
  ["外面正在下雨。","Wàimiàn zhèngzài xiàyǔ.","It's raining outside."],
  ["如果你有时间，我们可以见面。","Rúguǒ nǐ yǒu shíjiān, wǒmen kěyǐ jiànmiàn.","If you have time, we can meet."],
  ["我想跟你聊聊。","Wǒ xiǎng gēn nǐ liáoliao.","I want to chat with you."],
  ["别生气了。","Bié shēngqì le.","Don't be angry."],
  ["我很想去，可是我没有时间。","Wǒ hěn xiǎng qù, kěshì wǒ méiyǒu shíjiān.","I really want to go, but I don't have time."],
  ["这个地方挺不错的。","Zhège dìfang tǐng búcuò de.","This place is quite nice."],
  ["她说话很亲切。","Tā shuōhuà hěn qīnqiè.","She speaks very warmly."],
  ["我不知道答案。","Wǒ bù zhīdào dá'àn.","I don't know the answer."],
  ["谢谢你这么关心我。","Xièxie nǐ zhème guānxīn wǒ.","Thank you for caring about me so much."],
  ["请回答这个问题。","Qǐng huídá zhège wèntí.","Please answer this question."],
  ["这是一个很有名的成语。","Zhè shì yí ge hěn yǒumíng de chéngyǔ.","This is a very famous idiom."],
  ["这个词是什么意思？","Zhège cí shì shénme yìsi?","What does this word mean?"],
  ["这是一个很漂亮的地方。","Zhè shì yí ge hěn piàoliang de dìfang.","This is a very beautiful place."],
  ["每个地方都有自己的风俗。","Měi ge dìfang dōu yǒu zìjǐ de fēngsú.","Every place has its own customs."],
  ["我很后悔小时候没有好好儿学英语。","Wǒ hěn hòuhuǐ xiǎoshíhou méiyǒu hǎohāor xué Yīngyǔ.","I really regret not studying English properly as a child."],
  ["我在这里交到了一些朋友。","Wǒ zài zhèlǐ jiāo dào le yìxiē péngyou.","I've made some friends here."],
  ["她的包上有很多玩具。","Tā de bāo shàng yǒu hěn duō wánjù.","There are lots of toys on her bag."],
  ["在泰国，到处都有榴莲。","Zài Tàiguó, dàochù dōu yǒu liúlián.","In Thailand there's durian everywhere."],
  ["我很喜欢泰国的食物。","Wǒ hěn xǐhuan Tàiguó de shíwù.","I really like Thai food."],
  ["路上车很多，当心！","Lùshàng chē hěn duō, dāngxīn!","There are lots of cars on the road, be careful!"],
  ["我和中文很有缘分。","Wǒ hé Zhōngwén hěn yǒu yuánfèn.","Chinese and I were meant for each other."],
  ["学习汉语的过程很有趣。","Xuéxí Hànyǔ de guòchéng hěn yǒuqù.","The process of learning Chinese is very interesting."],
  ["谁对你的影响最大？","Shéi duì nǐ de yǐngxiǎng zuì dà?","Who has influenced you the most?"],
  ["你学过哪些语言？","Nǐ xué guo nǎxiē yǔyán?","Which languages have you studied?"],
  ["这方面我还需要练习。","Zhè fāngmiàn wǒ hái xūyào liànxí.","I still need practice in this area."],
  ["我每天都做中文阅读。","Wǒ měitiān dōu zuò Zhōngwén yuèdú.","I do Chinese reading every day."],
  ["我平时不喝酒。","Wǒ píngshí bù hē jiǔ.","I don't usually drink."],
  ["我是六年前开始学汉语的。","Wǒ shì liù nián qián kāishǐ xué Hànyǔ de.","I started learning Chinese six years ago."],
  ["中文很难，但是很有意思。","Zhōngwén hěn nán, dànshì hěn yǒu yìsi.","Chinese is hard, but very interesting."],
  ["他做什么事都很努力。","Tā zuò shénme shì dōu hěn nǔlì.","He works hard at everything he does."],
  ["这首歌现在很流行。","Zhè shǒu gē xiànzài hěn liúxíng.","This song is very popular now."],
  ["你要好好儿休息。","Nǐ yào hǎohāor xiūxi.","You should rest properly."],
  ["下个星期我还会再去。","Xià ge xīngqī wǒ hái huì zài qù.","I'll go again next week."],
  ["我还没适应这里的生活。","Wǒ hái méi shìyìng zhèlǐ de shēnghuó.","I still haven't adapted to life here."],
  ["大家都在唱这首歌。","Dàjiā dōu zài chàng zhè shǒu gē.","Everyone is singing this song."],
  ["我喜欢听中文歌。","Wǒ xǐhuan tīng Zhōngwén gē.","I like listening to Chinese songs."],
  ["这个假期你想去哪儿旅行？","Zhège jiàqī nǐ xiǎng qù nǎr lǚxíng?","Where do you want to travel this holiday?"],
  ["我小时候住在农村。","Wǒ xiǎoshíhou zhù zài nóngcūn.","I lived in the countryside when I was little."],
  ["他的英语说得很好。","Tā de Yīngyǔ shuō de hěn hǎo.","He speaks English very well."],
  ["有人说北京的夏天很热，其实不太热。","Yǒu rén shuō Běijīng de xiàtiān hěn rè, qíshí bú tài rè.","People say Beijing summers are hot; actually it's not that hot."],
  ["见到你我很高兴。","Jiàndào nǐ wǒ hěn gāoxìng.","I'm very happy to see you."],
  ["这个问题不太难。","Zhège wèntí bú tài nán.","This question isn't too difficult."],
  ["我怕吃辣的菜。","Wǒ pà chī là de cài.","I'm afraid of eating spicy food."],
  ["听说四川菜非常辣。","Tīngshuō Sìchuān cài fēicháng là.","I hear Sichuan food is extremely spicy."],
  ["你的汉语那么好！","Nǐ de Hànyǔ nàme hǎo!","Your Chinese is so good!"],
  ["你能告诉我怎么去车站吗？","Nǐ néng gàosu wǒ zěnme qù chēzhàn ma?","Can you tell me how to get to the station?"],
  ["我想提高我的汉语听说能力。","Wǒ xiǎng tígāo wǒ de Hànyǔ tīngshuō nénglì.","I want to improve my Chinese listening and speaking."],
  ["她的工作能力很强。","Tā de gōngzuò nénglì hěn qiáng.","Her work ability is very strong."],
  ["她的学习方法很好。","Tā de xuéxí fāngfǎ hěn hǎo.","Her study method is very good."],
  ["我不这样觉得。","Wǒ bú zhèyàng juéde.","I don't think so."],
  ["看完电影有点儿后悔。","Kàn wán diànyǐng yǒudiǎnr hòuhuǐ.","After watching the movie I regretted it a bit."],
  ["你不用担心。","Nǐ búyòng dānxīn.","You don't need to worry."],
  ["我六岁开始学中国功夫。","Wǒ liù suì kāishǐ xué Zhōngguó gōngfu.","I started learning Chinese kung fu at six."],
  ["成龙的功夫电影很有名。","Chéng Lóng de gōngfu diànyǐng hěn yǒumíng.","Jackie Chan's kung fu movies are very famous."],
  ["他不但教我功夫，而且教我做人的道理。","Tā búdàn jiāo wǒ gōngfu, érqiě jiāo wǒ zuòrén de dàoli.","He not only taught me kung fu, but also how to be a good person."],
  ["我的老师教我们汉语。","Wǒ de lǎoshī jiāo wǒmen Hànyǔ.","My teacher teaches us Chinese."],
  ["他教我很多做人的道理。","Tā jiāo wǒ hěn duō zuòrén de dàoli.","He taught me a lot about how to conduct myself."],
  ["你说的很有道理。","Nǐ shuō de hěn yǒu dàoli.","What you say makes a lot of sense."],
  ["后来我开始学习汉语。","Hòulái wǒ kāishǐ xuéxí Hànyǔ.","Later I started learning Chinese."],
  ["有人说学汉语没用。","Yǒu rén shuō xué Hànyǔ méiyòng.","Some people say learning Chinese is useless."],
  ["他想去大城市挣钱。","Tā xiǎng qù dà chéngshì zhèngqián.","He wants to go to a big city to earn money."],
  ["大家觉得这个工作没什么出息。","Dàjiā juéde zhège gōngzuò méi shénme chūxi.","Everyone thinks this job has no prospects."],
  ["我们一起喝中国茶。","Wǒmen yìqǐ hē Zhōngguó chá.","We drink Chinese tea together."],
  ["我很喜欢吃中国菜。","Wǒ hěn xǐhuan chī Zhōngguó cài.","I really like eating Chinese food."],
  ["我的家人也喜欢中国。","Wǒ de jiārén yě xǐhuan Zhōngguó.","My family also likes China."],
  ["我在找我的手机。","Wǒ zài zhǎo wǒ de shǒujī.","I'm looking for my phone."],
  ["我的生活里到处都有中国元素。","Wǒ de shēnghuó lǐ dàochù dōu yǒu Zhōngguó yuánsù.","There are Chinese elements everywhere in my life."],
  ["书架上放着很多中文书。","Shūjià shàng fàng zhe hěn duō Zhōngwén shū.","There are many Chinese books on the bookshelf."],
  ["我今天穿着唐装。","Wǒ jīntiān chuān zhe tángzhuāng.","I'm wearing a Tang suit today."],
  ["一年前我来中国留学。","Yì nián qián wǒ lái Zhōngguó liúxué.","A year ago I came to China to study."],
  ["我的学费是自己挣的。","Wǒ de xuéfèi shì zìjǐ zhèng de.","I earned my tuition myself."],
  ["假期我在餐厅打工。","Jiàqī wǒ zài cāntīng dǎgōng.","During the holiday I worked part-time at a restaurant."],
  ["我的汉语进步得很快。","Wǒ de Hànyǔ jìnbù de hěn kuài.","My Chinese is improving quickly."],
  ["我快毕业了。","Wǒ kuài bìyè le.","I'm about to graduate."],
  ["我明年毕业。","Wǒ míngnián bìyè.","I graduate next year."],
  ["我们用汉语聊天。","Wǒmen yòng Hànyǔ liáotiān.","We chat in Chinese."],
  ["我想当中国饭馆的厨师。","Wǒ xiǎng dāng Zhōngguó fànguǎn de chúshī.","I want to be a chef at a Chinese restaurant."],
  ["这家饭馆的菜很好吃。","Zhè jiā fànguǎn de cài hěn hǎochī.","The food at this restaurant is delicious."],
  ["他是一个很有名的厨师。","Tā shì yí ge hěn yǒumíng de chúshī.","He is a very famous chef."],
  ["我最喜欢吃宫保鸡丁。","Wǒ zuì xǐhuan chī gōngbǎo jīdīng.","My favorite dish is Kung Pao chicken."],
  ["麻婆豆腐有点儿辣。","Mápó dòufu yǒudiǎnr là.","Mapo tofu is a little spicy."],
  ["这个菜真好吃！","Zhège cài zhēn hǎochī!","This dish is really delicious!"],
  ["一想起来家乡的菜，我就想回家。","Yì xiǎng qǐlái jiāxiāng de cài, wǒ jiù xiǎng huí jiā.","As soon as I think of my hometown's food, I want to go home."],
  ["一想到宫保鸡丁我就流口水。","Yì xiǎngdào gōngbǎo jīdīng wǒ jiù liú kǒushuǐ.","Just thinking of Kung Pao chicken makes me drool."],
  ["给中国人当导游也不错。","Gěi Zhōngguórén dāng dǎoyóu yě búcuò.","Being a tour guide for Chinese people is also not bad."],
  ["这个主意不错。","Zhège zhǔyi búcuò.","This idea is pretty good."],
  ["我很讨厌堵车。","Wǒ hěn tǎoyàn dǔchē.","I really hate traffic jams."],
  ["她在咖啡店当咖啡师。","Tā zài kāfēidiàn dāng kāfēishī.","She works as a barista at a café."],
  ["我想自己开一家公司。","Wǒ xiǎng zìjǐ kāi yì jiā gōngsī.","I want to start my own company."],
  ["你想好下个月去哪儿了吗？","Nǐ xiǎnghǎo xià ge yuè qù nǎr le ma?","Have you decided where to go next month?"],
  ["我的工作一定和中国有关系。","Wǒ de gōngzuò yídìng hé Zhōngguó yǒu guānxi.","My job will definitely be connected with China."],
  ["汉语越学越有意思。","Hànyǔ yuè xué yuè yǒu yìsi.","The more you learn Chinese, the more interesting it gets."],
  ["他越说，我越不懂。","Tā yuè shuō, wǒ yuè bù dǒng.","The more he talked, the less I understood."],
  ["你明白我的意思吗？","Nǐ míngbai wǒ de yìsi ma?","Do you understand what I mean?"],
  ["你误解我了。","Nǐ wùjiě wǒ le.","You misunderstood me."],
  ["老师越表扬学生，学生就越努力。","Lǎoshī yuè biǎoyáng xuésheng, xuésheng jiù yuè nǔlì.","The more the teacher praises the students, the harder they work."],
  ["你越怕做错，越会做错。","Nǐ yuè pà zuò cuò, yuè huì zuò cuò.","The more afraid you are of mistakes, the more you make them."],
  ["西瓜越红越好吃。","Xīguā yuè hóng yuè hǎochī.","The redder the watermelon, the tastier it is."],
  ["我们在下一站下车。","Wǒmen zài xià yí zhàn xiàchē.","We get off at the next stop."],
  ["东西不是越便宜越好。","Dōngxi bú shì yuè piányi yuè hǎo.","Things aren't necessarily better the cheaper they are."],
  ["我想当老师。","Wǒ xiǎng dāng lǎoshī.","I want to be a teacher."],
  ["我十一点要出门。","Wǒ shíyī diǎn yào chūmén.","I have to go out at eleven."],
  ["这本书很有趣。","Zhè běn shū hěn yǒuqù.","This book is very interesting."],
  ["雨越下越大。","Yǔ yuè xià yuè dà.","The rain is getting heavier and heavier."],
  ["我一起床就上网。","Wǒ yì qǐchuáng jiù shàngwǎng.","As soon as I get up, I go online."],
  ["我先看邮件，然后吃早饭。","Wǒ xiān kàn yóujiàn, ránhòu chī zǎofàn.","I check my email first, then eat breakfast."],
  ["我每天早上都上网。","Wǒ měitiān zǎoshang dōu shàngwǎng.","I go online every morning."],
  ["请打开你的电子邮箱。","Qǐng dǎkāi nǐ de diànzǐ yóuxiāng.","Please open your email inbox."],
  ["我的电子邮箱里有很多新邮件。","Wǒ de diànzǐ yóuxiāng lǐ yǒu hěn duō xīn yóujiàn.","There are many new emails in my inbox."],
  ["有空常给我们发电子邮件。","Yǒu kòng cháng gěi wǒmen fā diànzǐ yóujiàn.","Email us often when you have time."],
  ["你有没有收到我的邮件？","Nǐ yǒu méiyǒu shōudào wǒ de yóujiàn?","Did you receive my email?"],
  ["看邮件成了我的习惯。","Kàn yóujiàn chéng le wǒ de xíguàn.","Checking email has become my habit."],
  ["我收到了你的消息。","Wǒ shōudào le nǐ de xiāoxi.","I received your message."],
  ["收到你的邮件，我们高兴极了。","Shōudào nǐ de yóujiàn, wǒmen gāoxìng jí le.","We were extremely happy to get your email."],
  ["你那里的情况怎么样？","Nǐ nàlǐ de qíngkuàng zěnmeyàng?","How is the situation over there?"],
  ["我得好好儿感谢你。","Wǒ děi hǎohāor gǎnxiè nǐ.","I really have to thank you."],
  ["我给你发了一条消息。","Wǒ gěi nǐ fā le yì tiáo xiāoxi.","I sent you a message."],
  ["你有微信吗？","Nǐ yǒu Wēixìn ma?","Do you have WeChat?"],
  ["这是一个好消息。","Zhè shì yí ge hǎo xiāoxi.","This is good news."],
  ["妈妈对你有点儿不放心。","Māma duì nǐ yǒudiǎnr bú fàngxīn.","Mom is a little worried about you."],
  ["你已经不是小孩子了。","Nǐ yǐjīng bú shì xiǎoháizi le.","You're not a little kid anymore."],
  ["你最近身体怎么样？","Nǐ zuìjìn shēntǐ zěnmeyàng?","How has your health been lately?"],
  ["老师讲课讲得很清楚。","Lǎoshī jiǎngkè jiǎng de hěn qīngchu.","The teacher lectures very clearly."],
  ["老师讲课你听得懂吗？","Lǎoshī jiǎngkè nǐ tīng de dǒng ma?","Can you understand the teacher's lectures?"],
  ["中国菜你吃得惯吗？","Zhōngguó cài nǐ chī de guàn ma?","Are you used to eating Chinese food?"],
  ["妈妈有很多话要和你说。","Māma yǒu hěn duō huà yào hé nǐ shuō.","Mom has a lot to say to you."],
  ["可惜我的眼睛越来越不好。","Kěxī wǒ de yǎnjing yuèláiyuè bù hǎo.","Unfortunately my eyesight is getting worse."],
  ["她的眼睛很大。","Tā de yǎnjing hěn dà.","Her eyes are big."],
  ["你什么时候有空？","Nǐ shénme shíhou yǒu kòng?","When are you free?"],
  ["有空常来玩。","Yǒu kòng cháng lái wán.","Come visit often when you're free."],
  ["祝你快乐！","Zhù nǐ kuàilè!","Wishing you happiness!"],
  ["我的手机没电了。","Wǒ de shǒujī méi diàn le.","My phone is out of battery."],
  ["电脑没电了，我要充电。","Diànnǎo méi diàn le, wǒ yào chōngdiàn.","The computer is out of battery, I need to charge it."],
  ["我要给手机充电。","Wǒ yào gěi shǒujī chōngdiàn.","I need to charge my phone."],
  ["你带充电器了吗？","Nǐ dài chōngdiànqì le ma?","Did you bring the charger?"],
  ["你第一次离开家乡是什么时候？","Nǐ dì yī cì líkāi jiāxiāng shì shénme shíhou?","When was the first time you left your hometown?"],
  ["我拿到了护照。","Wǒ nádào le hùzhào.","I got my passport."],
  ["出国旅行需要护照。","Chūguó lǚxíng xūyào hùzhào.","You need a passport to travel abroad."],
  ["想拿到护照需要什么条件？","Xiǎng nádào hùzhào xūyào shénme tiáojiàn?","What are the requirements for getting a passport?"],
  ["希望天气好一点。","Xīwàng tiānqì hǎo yìdiǎn.","I hope the weather gets a bit better."],
  ["亲爱的妈妈，您好！","Qīn'ài de māma, nín hǎo!","Dear Mom, hello!"],
  ["您最近身体怎么样？","Nín zuìjìn shēntǐ zěnmeyàng?","How has your health been lately?"],
  ["每次看到您的邮件，我都很高兴。","Měi cì kàndào nín de yóujiàn, wǒ dōu hěn gāoxìng.","Every time I see your email, I'm very happy."],
  ["我好像看到了您的笑脸。","Wǒ hǎoxiàng kàndào le nín de xiàoliǎn.","It's as if I saw your smiling face."],
  ["我闻到了饭菜的香味儿。","Wǒ wéndào le fàncài de xiāngwèir.","I smelled the aroma of the food."],
  ["厨房里有很好的香味儿。","Chúfáng lǐ yǒu hěn hǎo de xiāngwèir.","There's a lovely aroma in the kitchen."],
  ["妈妈做的饭菜很好吃。","Māma zuò de fàncài hěn hǎochī.","The food Mom cooks is delicious."],
  ["我有点儿想家了。","Wǒ yǒudiǎnr xiǎng jiā le.","I miss home a little."],
  ["我在这里有许多朋友。","Wǒ zài zhèlǐ yǒu xǔduō péngyou.","I have many friends here."],
  ["我这里的一切都很好。","Wǒ zhèlǐ de yíqiè dōu hěn hǎo.","Everything here is fine."],
  ["别担心，我很好。","Bié dānxīn, wǒ hěn hǎo.","Don't worry, I'm fine."],
  ["请别为我担心。","Qǐng bié wèi wǒ dānxīn.","Please don't worry about me."],
  ["我跟朋友学会了做中国菜。","Wǒ gēn péngyou xuéhuì le zuò Zhōngguó cài.","I learned to cook Chinese food from my friends."],
  ["我买了几个西红柿。","Wǒ mǎi le jǐ ge xīhóngshì.","I bought a few tomatoes."],
  ["我做的西红柿炒鸡蛋好吃极了。","Wǒ zuò de xīhóngshì chǎo jīdàn hǎochī jí le.","The tomato and egg I make is extremely tasty."],
  ["我和室友打算搬家。","Wǒ hé shìyǒu dǎsuàn bānjiā.","My roommate and I plan to move."],
  ["你假期打算做什么？","Nǐ jiàqī dǎsuàn zuò shénme?","What do you plan to do during the holiday?"],
  ["我们想搬到学校附近去住。","Wǒmen xiǎng bān dào xuéxiào fùjìn qù zhù.","We want to move near the school."],
  ["告诉您一个秘密。","Gàosu nín yí ge mìmì.","Let me tell you a secret."],
  ["我们班有一个中国姑娘。","Wǒmen bān yǒu yí ge Zhōngguó gūniang.","There's a Chinese girl in our class."],
  ["那个姑娘很聪明。","Nàge gūniang hěn cōngmíng.","That girl is very smart."],
  ["她又漂亮又聪明。","Tā yòu piàoliang yòu cōngmíng.","She is both pretty and smart."],
  ["我真的太忙了。","Wǒ zhēn de tài máng le.","I'm really too busy."],
  ["这个菜太好吃了！","Zhège cài tài hǎochī le!","This dish is so delicious!"],
  ["祝您身体健康！","Zhù nín shēntǐ jiànkāng!","Wishing you good health!"],
  ["其他的问题以后再说。","Qítā de wèntí yǐhòu zài shuō.","We'll talk about the other issues later."],
  ["我很喜欢吃空心菜。","Wǒ hěn xǐhuan chī kōngxīncài.","I really like water spinach."],
  ["对不起，我来晚了。","Duìbuqǐ, wǒ lái wǎn le.","Sorry, I'm late."],
  ["我想家乡的咖啡馆。","Wǒ xiǎng jiāxiāng de kāfēiguǎn.","I miss the cafés in my hometown."],
  ["天气好的时候我们出去玩。","Tiānqì hǎo de shíhou wǒmen chūqù wán.","When the weather is nice we go out."]
];
