const EXAMPLES_A = [
  ["我们周末去海边玩。","Wǒmen zhōumò qù hǎibiān wán.","We go to the beach on the weekend."],
  ["你能推荐一家餐厅吗？","Nǐ néng tuījiàn yì jiā cāntīng ma?","Can you recommend a restaurant?"],
  ["我通常七点起床。","Wǒ tōngcháng qī diǎn qǐchuáng.","I usually get up at seven."],
  ["我很喜欢吃豆腐。","Wǒ hěn xǐhuan chī dòufǔ.","I really like eating tofu."],
  ["他喜欢玩电子游戏。","Tā xǐhuan wán diànzǐ yóuxì.","He likes playing video games."],
  ["我来介绍一下我的朋友。","Wǒ lái jièshào yíxià wǒ de péngyou.","Let me introduce my friend."],
  ["她是一个有名的歌手。","Tā shì yí ge yǒumíng de gēshǒu.","She is a famous singer."],
  ["这个演员很受欢迎。","Zhège yǎnyuán hěn shòu huānyíng.","This actor is very popular."],
  ["这首歌很流行。","Zhè shǒu gē hěn liúxíng.","This song is very popular."],
  ["今天我的心情很好。","Jīntiān wǒ de xīnqíng hěn hǎo.","My mood is good today."],
  ["天气影响我的心情。","Tiānqì yǐngxiǎng wǒ de xīnqíng.","The weather affects my mood."],
  ["我只有十块钱。","Wǒ zhǐ yǒu shí kuài qián.","I only have ten yuan."],
  ["不要只看外表。","Búyào zhǐ kàn wàibiǎo.","Don't only look at the appearance."],
  ["他的外貌很普通。","Tā de wàimào hěn pǔtōng.","His appearance is very ordinary."],
  ["你的老师长什么样？","Nǐ de lǎoshī zhǎng shénme yàng?","What does your teacher look like?"],
  ["他长得很帅。","Tā zhǎng de hěn shuài.","He is very handsome."],
  ["这里的风景很美。","Zhèlǐ de fēngjǐng hěn měi.","The scenery here is beautiful."],
  ["她穿了一条漂亮的裙子。","Tā chuān le yì tiáo piàoliang de qúnzi.","She wore a pretty dress."],
  ["这部电影很好看。","Zhè bù diànyǐng hěn hǎokàn.","This movie is really good."],
  ["这只狗有点丑。","Zhè zhī gǒu yǒudiǎn chǒu.","This dog is a bit ugly."],
  ["这件衣服不好看。","Zhè jiàn yīfu bù hǎokàn.","This piece of clothing is not good-looking."],
  ["他长得很高。","Tā zhǎng de hěn gāo.","He is very tall."],
  ["我比他矮一点。","Wǒ bǐ tā ǎi yìdiǎn.","I am a little shorter than him."],
  ["这只猫有点胖。","Zhè zhī māo yǒudiǎn pàng.","This cat is a bit fat."],
  ["她很瘦。","Tā hěn shòu.","She is very thin."],
  ["我的爷爷很老了。","Wǒ de yéye hěn lǎo le.","My grandpa is very old."],
  ["他有一米八多。","Tā yǒu yì mǐ bā duō.","He is over 1.8 meters tall."],
  ["我来中国不到一年。","Wǒ lái Zhōngguó búdào yì nián.","I've been in China less than a year."],
  ["她的头发很长。","Tā de tóufa hěn cháng.","Her hair is very long."],
  ["这条河很长。","Zhè tiáo hé hěn cháng.","This river is very long."],
  ["他的头发很短。","Tā de tóufa hěn duǎn.","His hair is very short."],
  ["她有卷头发。","Tā yǒu juǎn tóufa.","She has curly hair."],
  ["我的头发是直的。","Wǒ de tóufa shì zhí de.","My hair is straight."],
  ["他有很长的胡子。","Tā yǒu hěn cháng de húzi.","He has a long beard."],
  ["他想留胡子。","Tā xiǎng liú húzi.","He wants to grow a beard."],
  ["我每天戴眼镜。","Wǒ měitiān dài yǎnjìng.","I wear glasses every day."],
  ["他戴着一副金边眼镜。","Tā dài zhe yí fù jīnbiān yǎnjìng.","He is wearing gold-rimmed glasses."],
  ["她害羞地脸红了。","Tā hàixiū de liǎnhóng le.","She blushed shyly."],
  ["你喜欢什么颜色？","Nǐ xǐhuan shénme yánsè?","What color do you like?"],
  ["他有一头黑头发。","Tā yǒu yì tóu hēi tóufa.","He has a head of black hair."],
  ["她的眼睛是棕色的。","Tā de yǎnjing shì zōngsè de.","Her eyes are brown."],
  ["她有金色的头发。","Tā yǒu jīnsè de tóufa.","She has golden hair."],
  ["我喜欢红色。","Wǒ xǐhuan hóngsè.","I like the color red."],
  ["天空是蓝色的。","Tiānkōng shì lánsè de.","The sky is blue."],
  ["树叶是绿色的。","Shùyè shì lǜsè de.","The leaves are green."],
  ["我喜欢深蓝色。","Wǒ xǐhuan shēn lánsè.","I like dark blue."],
  ["这是浅绿色。","Zhè shì qiǎn lǜsè.","This is light green."],
  ["她的性格很好。","Tā de xìnggé hěn hǎo.","She has a good personality."],
  ["他是一个外向的人。","Tā shì yí ge wàixiàng de rén.","He is an extroverted person."],
  ["她很开朗。","Tā hěn kāilǎng.","She is very cheerful."],
  ["他是一个阳光的男孩。","Tā shì yí ge yángguāng de nánhái.","He is a sunny, cheerful boy."],
  ["我比较内向。","Wǒ bǐjiào nèixiàng.","I am rather introverted."],
  ["这个房间很安静。","Zhège fángjiān hěn ānjìng.","This room is very quiet."],
  ["这个孩子很害羞。","Zhège háizi hěn hàixiū.","This child is very shy."],
  ["他看起来有点忧郁。","Tā kàn qǐlái yǒudiǎn yōuyù.","He looks a bit gloomy."],
  ["我是一个e人。","Wǒ shì yí ge e rén.","I'm an 'e person' (an extrovert)."],
  ["他是一个i人。","Tā shì yí ge i rén.","He is an 'i person' (an introvert)."],
  ["今天比较冷。","Jīntiān bǐjiào lěng.","Today is relatively cold."],
  ["这个学生很聪明。","Zhège xuésheng hěn cōngmíng.","This student is very smart."],
  ["他很幽默。","Tā hěn yōumò.","He is very humorous."],
  ["她在学校很受欢迎。","Tā zài xuéxiào hěn shòu huānyíng.","She is very popular at school."],
  ["他一边吃饭一边看电视。","Tā yìbiān chīfàn yìbiān kàn diànshì.","He watches TV while eating."],
  ["他也许不来了。","Tā yěxǔ bù lái le.","Maybe he won't come."],
  ["我们继续学习吧。","Wǒmen jìxù xuéxí ba.","Let's continue studying."],
  ["我们休息一下吧。","Wǒmen xiūxi yíxià ba.","Let's take a break."],
  ["我每天学习中文。","Wǒ měitiān xuéxí Zhōngwén.","I study Chinese every day."],
  ["我的学校很大。","Wǒ de xuéxiào hěn dà.","My school is very big."],
  ["发生了什么事？","Fāshēng le shénme shì?","What happened?"],
  ["我已经吃饭了。","Wǒ yǐjīng chīfàn le.","I have already eaten."],
  ["会议结束了。","Huìyì jiéshù le.","The meeting has ended."],
  ["今天我起得很早。","Jīntiān wǒ qǐ de hěn zǎo.","I got up very early today."],
  ["明天我们早一点出发。","Míngtiān wǒmen zǎo yìdiǎn chūfā.","Let's leave a little earlier tomorrow."],
  ["我今天有一节课。","Wǒ jīntiān yǒu yì jié kè.","I have one class today."],
  ["下节课是数学。","Xià jié kè shì shùxué.","The next class is math."],
  ["他昨天逃课了。","Tā zuótiān táokè le.","He skipped class yesterday."],
  ["我喜欢数学。","Wǒ xǐhuan shùxué.","I like math."],
  ["人生很短。","Rénshēng hěn duǎn.","Life is short."],
  ["我的生活很简单。","Wǒ de shēnghuó hěn jiǎndān.","My life is very simple."],
  ["我们见面的时候很开心。","Wǒmen jiànmiàn de shíhou hěn kāixīn.","We are happy when we meet."],
  ["你什么时候来？","Nǐ shénme shíhou lái?","When are you coming?"],
  ["我明天离开北京。","Wǒ míngtiān líkāi Běijīng.","I'm leaving Beijing tomorrow."],
  ["我的工作很忙。","Wǒ de gōngzuò hěn máng.","My work is very busy."],
  ["我有时去跑步。","Wǒ yǒushí qù pǎobù.","Sometimes I go running."],
  ["我偶尔喝咖啡。","Wǒ ǒu'ěr hē kāfēi.","I occasionally drink coffee."],
  ["他经常迟到。","Tā jīngcháng chídào.","He is often late."],
  ["请等一会。","Qǐng děng yíhuìr.","Please wait a moment."],
  ["我八点上班。","Wǒ bā diǎn shàngbān.","I go to work at eight."],
  ["我五点下班。","Wǒ wǔ diǎn xiàbān.","I get off work at five."],
  ["他仍然在睡觉。","Tā réngrán zài shuìjiào.","He is still sleeping."],
  ["学校有很多活动。","Xuéxiào yǒu hěn duō huódòng.","The school has many activities."],
  ["我们去看电影吧。","Wǒmen qù kàn diànyǐng ba.","Let's go watch a movie."],
  ["我喜欢看中国电视剧。","Wǒ xǐhuan kàn Zhōngguó diànshìjù.","I like watching Chinese TV series."],
  ["你想一想再回答。","Nǐ xiǎng yi xiǎng zài huídá.","Think about it before you answer."],
  ["我们有不同的想法。","Wǒmen yǒu bùtóng de xiǎngfǎ.","We have different ideas."],
  ["你应该多休息。","Nǐ yīnggāi duō xiūxi.","You should rest more."],
  ["你一定要来。","Nǐ yídìng yào lái.","You must come."],
  ["这是一本无聊的书。","Zhè shì yì běn wúliáo de shū.","This is a boring book."],
  ["这是一个有趣的故事。","Zhè shì yí ge yǒuqù de gùshi.","This is an interesting story."],
  ["这个问题很简单。","Zhège wèntí hěn jiǎndān.","This question is very simple."],
  ["考试前要复习。","Kǎoshì qián yào fùxí.","Review before the exam."],
  ["北京是一个大城市。","Běijīng shì yí ge dà chéngshì.","Beijing is a big city."],
  ["这是一个著名的地方。","Zhè shì yí ge zhùmíng de dìfang.","This is a famous place."],
  ["北京是中国的首都。","Běijīng shì Zhōngguó de shǒudū.","Beijing is the capital of China."],
  ["夜市很热闹。","Yèshì hěn rènao.","The night market is very lively."],
  ["清迈在泰国的北部。","Qīngmài zài Tàiguó de běibù.","Chiang Mai is in northern Thailand."],
  ["这里的生活节奏很慢。","Zhèlǐ de shēnghuó jiézòu hěn màn.","The pace of life here is slow."],
  ["他走得很慢。","Tā zǒu de hěn màn.","He walks very slowly."],
  ["两个城市各有各的魅力。","Liǎng ge chéngshì gè yǒu gè de mèilì.","Each of the two cities has its own charm."],
  ["这个城市很有魅力。","Zhège chéngshì hěn yǒu mèilì.","This city is very charming."],
  ["这里的街道很安全。","Zhèlǐ de jiēdào hěn ānquán.","The streets here are very safe."],
  ["这条街道很干净。","Zhè tiáo jiēdào hěn gānjìng.","This street is very clean."],
  ["曼谷是一个现代的城市。","Mànggǔ shì yí ge xiàndài de chéngshì.","Bangkok is a modern city."],
  ["那里有很多高楼。","Nàlǐ yǒu hěn duō gāo lóu.","There are many tall buildings there."],
  ["我们去商场买东西。","Wǒmen qù shāngchǎng mǎi dōngxi.","We go to the mall to buy things."],
  ["这里的交通四通八达。","Zhèlǐ de jiāotōng sìtōngbādá.","The transport here reaches everywhere."],
  ["我坐轻轨去上班。","Wǒ zuò qīngguǐ qù shàngbān.","I take the light rail to work."],
  ["坐地铁很方便。","Zuò dìtiě hěn fāngbiàn.","Taking the subway is convenient."],
  ["曼谷的夜生活很丰富。","Mànggǔ de yèshēnghuó hěn fēngfù.","Bangkok's nightlife is rich."],
  ["这里的活动很丰富。","Zhèlǐ de huódòng hěn fēngfù.","The activities here are abundant."],
  ["晚上我们去酒吧。","Wǎnshang wǒmen qù jiǔbā.","We go to a bar at night."],
  ["我喜欢逛夜市。","Wǒ xǐhuan guàng yèshì.","I like strolling the night market."],
  ["即使下雨，我也要去。","Jíshǐ xiàyǔ, wǒ yě yào qù.","Even if it rains, I will still go."],
  ["今天特别热。","Jīntiān tèbié rè.","Today is especially hot."],
  ["地铁里很拥挤。","Dìtiě lǐ hěn yōngjǐ.","It is very crowded in the subway."],
  ["我们在公园散步。","Wǒmen zài gōngyuán sànbù.","We take a walk in the park."],
  ["总的来说，这里很好。","Zǒng de lái shuō, zhèlǐ hěn hǎo.","Generally speaking, it's nice here."],
  ["他走路很快。","Tā zǒulù hěn kuài.","He walks fast."],
  ["这里的交通很堵。","Zhèlǐ de jiāotōng hěn dǔ.","The traffic here is congested."],
  ["早上路很堵。","Zǎoshang lù hěn dǔ.","The roads are jammed in the morning."],
  ["祝你快乐！","Zhù nǐ kuàilè!","Wishing you happiness!"],
  ["这两个城市完全不同。","Zhè liǎng ge chéngshì wánquán bùtóng.","These two cities are completely different."],
  ["他喜欢骑自行车。","Tā xǐhuan qí zìxíngchē.","He likes riding a bicycle."],
  ["我每天骑自行车。","Wǒ měitiān qí zìxíngchē.","I ride a bike every day."],
  ["我们走路或者坐车。","Wǒmen zǒulù huòzhě zuòchē.","We walk or take a car."],
  ["我喜欢走路上班。","Wǒ xǐhuan zǒulù shàngbān.","I like walking to work."],
  ["这是一座古老的寺庙。","Zhè shì yí zuò gǔlǎo de sìmiào.","This is an ancient temple."],
  ["清迈有很多寺庙。","Qīngmài yǒu hěn duō sìmiào.","Chiang Mai has many temples."],
  ["我喜欢传统建筑。","Wǒ xǐhuan chuántǒng jiànzhù.","I like traditional architecture."],
  ["这里的建筑很漂亮。","Zhèlǐ de jiànzhù hěn piàoliang.","The buildings here are beautiful."],
  ["这里的文化气息很浓。","Zhèlǐ de wénhuà qìxī hěn nóng.","This place has a strong cultural atmosphere."],
  ["这杯咖啡很浓。","Zhè bēi kāfēi hěn nóng.","This cup of coffee is strong."],
  ["别着急，慢慢来。","Bié zháojí, mànmàn lái.","Don't rush, take it slow."],
  ["我们喜欢慢慢聊天。","Wǒmen xǐhuan mànmàn liáotiān.","We like to chat slowly."],
  ["曼谷很繁华。","Mànggǔ hěn fánhuá.","Bangkok is very bustling."],
  ["他们的生活方式不同。","Tāmen de shēnghuó fāngshì bùtóng.","Their lifestyles are different."],
  ["很多年轻人喜欢这里。","Hěn duō niánqīngrén xǐhuan zhèlǐ.","Many young people like it here."],
  ["我工作很忙。","Wǒ gōngzuò hěn máng.","I'm very busy with work."],
  ["我们去购物中心。","Wǒmen qù gòuwù zhōngxīn.","We go to the shopping center."],
  ["下班后我们去电影院。","Xiàbān hòu wǒmen qù diànyǐngyuàn.","After work we go to the cinema."],
  ["周末我想放松一下。","Zhōumò wǒ xiǎng fàngsōng yíxià.","I want to relax a bit on the weekend."],
  ["他们更喜欢自然。","Tāmen gèng xǐhuan zìrán.","They prefer nature more."],
  ["周末我去爬山。","Zhōumò wǒ qù páshān.","I go hiking on the weekend."],
  ["我们周末去爬山。","Wǒmen zhōumò qù páshān.","We go hiking on the weekend."],
  ["这个瀑布很美。","Zhège pùbù hěn měi.","This waterfall is beautiful."],
  ["他们去农场玩。","Tāmen qù nóngchǎng wán.","They go to the farm for fun."],
  ["我喜欢做瑜伽。","Wǒ xǐhuan zuò yújiā.","I like doing yoga."],
  ["她每天早上冥想。","Tā měitiān zǎoshang míngxiǎng.","She meditates every morning."],
  ["这里有很多瑜伽课程。","Zhèlǐ yǒu hěn duō yújiā kèchéng.","There are many yoga courses here."],
  ["这里有很多咖啡店。","Zhèlǐ yǒu hěn duō kāfēidiàn.","There are many cafés here."],
  ["我喜欢艺术。","Wǒ xǐhuan yìshù.","I like art."],
  ["我们去看艺术展览。","Wǒmen qù kàn yìshù zhǎnlǎn.","We go to see an art exhibition."],
  ["我喜欢逛街。","Wǒ xǐhuan guàngjiē.","I like strolling around the shops."],
  ["这个星期我想去博物馆。","Zhège xīngqī wǒ xiǎng qù bówùguǎn.","This week I want to go to the museum."],
  ["博物馆在市中心旁边。","Bówùguǎn zài shìzhōngxīn pángbiān.","The museum is next to the city center."],
  ["这里的文化气息很浓。","Zhèlǐ de wénhuà qìxī hěn nóng.","The cultural vibe here is strong."],
  ["我住在市中心。","Wǒ zhù zài shìzhōngxīn.","I live in the city center."],
  ["明天我休假。","Míngtiān wǒ xiūjià.","Tomorrow I'm on leave."],
  ["我读了一篇文章。","Wǒ dú le yì piān wénzhāng.","I read an article."],
  ["我需要时间适应新环境。","Wǒ xūyào shíjiān shìyìng xīn huánjìng.","I need time to adapt to the new environment."],
  ["这里的环境很好。","Zhèlǐ de huánjìng hěn hǎo.","The environment here is nice."],
  ["这件事不容易。","Zhè jiàn shì bù róngyì.","This thing isn't easy."],
  ["我刚到这里。","Wǒ gāng dào zhèlǐ.","I just arrived here."],
  ["这里太吵了。","Zhèlǐ tài chǎo le.","It's too noisy here."],
  ["街上有很多摩托车。","Jiē shàng yǒu hěn duō mótuōchē.","There are many motorcycles on the street."],
  ["这里的声音很大。","Zhèlǐ de shēngyīn hěn dà.","The sound here is very loud."],
  ["音乐声很响。","Yīnyuè shēng hěn xiǎng.","The music is very loud."],
  ["地铁里很挤。","Dìtiě lǐ hěn jǐ.","The subway is very crowded."],
  ["商场里满是人。","Shāngchǎng lǐ mǎn shì rén.","The mall is full of people."],
  ["我今天很累。","Wǒ jīntiān hěn lèi.","I'm very tired today."],
  ["慢慢地你会习惯这种节奏。","Mànmàn de nǐ huì xíguàn zhè zhǒng jiézòu.","Slowly you'll get used to this pace."],
  ["你会发现这里很方便。","Nǐ huì fāxiàn zhèlǐ hěn fāngbiàn.","You'll discover it's convenient here."],
  ["坐地铁很方便。","Zuò dìtiě hěn fāngbiàn.","Taking the subway is convenient."],
  ["这里到处都是便利店。","Zhèlǐ dàochù dōu shì biànlìdiàn.","There are convenience stores everywhere here."],
  ["楼下有一家便利店。","Lóu xià yǒu yì jiā biànlìdiàn.","There's a convenience store downstairs."],
  ["这家餐厅很好吃。","Zhè jiā cāntīng hěn hǎochī.","This restaurant is delicious."],
  ["我坐出租车去机场。","Wǒ zuò chūzūchē qù jīchǎng.","I take a taxi to the airport."],
  ["这里有很多游客。","Zhèlǐ yǒu hěn duō yóukè.","There are many tourists here."],
  ["这个区域很安全。","Zhège qūyù hěn ānquán.","This area is very safe."],
  ["这本书很有意思。","Zhè běn shū hěn yǒu yìsi.","This book is very interesting."],
  ["你可以自己选择。","Nǐ kěyǐ zìjǐ xuǎnzé.","You can choose for yourself."],
  ["九点以后商店就关门了。","Jiǔ diǎn yǐhòu shāngdiàn jiù guānmén le.","After nine the shops close."],
  ["这家商店很大。","Zhè jiā shāngdiàn hěn dà.","This shop is very big."],
  ["商店晚上九点关门。","Shāngdiàn wǎnshang jiǔ diǎn guānmén.","The shop closes at nine at night."],
  ["街上的人变少了。","Jiē shàng de rén biàn shǎo le.","There are fewer people on the street now."],
  ["这里的人很少。","Zhèlǐ de rén hěn shǎo.","There are few people here."],
  ["慢慢感受这里的生活。","Mànmàn gǎnshòu zhèlǐ de shēnghuó.","Slowly experience life here."],
  ["在寺庙里我感到很平静。","Zài sìmiào lǐ wǒ gǎndào hěn píngjìng.","In the temple I feel very calm."],
  ["时间好像走得更慢。","Shíjiān hǎoxiàng zǒu de gèng màn.","Time seems to move more slowly."],
  ["这个城市适合内向的人。","Zhège chéngshì shìhé nèixiàng de rén.","This city suits introverted people."],
  ["她是一个活泼的人。","Tā shì yí ge huópo de rén.","She is a lively person."],
  ["我想认识新朋友。","Wǒ xiǎng rènshi xīn péngyou.","I want to meet new friends."],
  ["这里有很多活动可以参加。","Zhèlǐ yǒu hěn duō huódòng kěyǐ cānjiā.","There are many activities to join here."],
  ["我喜欢独处的时间。","Wǒ xǐhuan dúchǔ de shíjiān.","I like time alone."],
  ["我很享受清迈的安静。","Wǒ hěn xiǎngshòu Qīngmài de ānjìng.","I really enjoy the quiet of Chiang Mai."],
  ["我需要自己的空间。","Wǒ xūyào zìjǐ de kōngjiān.","I need my own space."],
  ["每个人的看法都不同。","Měi ge rén de kànfǎ dōu bùtóng.","Everyone's view is different."],
  ["我的看法会随着时间改变。","Wǒ de kànfǎ huì suízhe shíjiān gǎibiàn.","My views change over time."],
  ["刚开始我不习惯。","Gāng kāishǐ wǒ bù xíguàn.","At first I wasn't used to it."],
  ["这个地方有点偏远。","Zhège dìfang yǒudiǎn piānyuǎn.","This place is a bit remote."],
  ["住久了你就会喜欢。","Zhù jiǔ le nǐ jiù huì xǐhuan.","After living here a while you'll like it."],
  ["曼谷的夜生活很精彩。","Mànggǔ de yèshēnghuó hěn jīngcǎi.","Bangkok's nightlife is exciting."],
  ["清迈的大自然很美丽。","Qīngmài de dàzìrán hěn měilì.","Chiang Mai's nature is beautiful."],
  ["交朋友很重要。","Jiāo péngyou hěn zhòngyào.","Making friends is important."],
  ["这是一件重要的事情。","Zhè shì yí jiàn zhòngyào de shìqing.","This is an important matter."],
  ["无论你在哪里，都要开心。","Wúlùn nǐ zài nǎlǐ, dōu yào kāixīn.","No matter where you are, be happy."],
  ["有朋友在身边很好。","Yǒu péngyou zài shēnbiān hěn hǎo.","It's nice to have friends by your side."],
  ["我通过工作认识了他。","Wǒ tōngguò gōngzuò rènshi le tā.","I met him through work."],
  ["我每天去健身。","Wǒ měitiān qù jiànshēn.","I work out every day."],
  ["我在上语言课。","Wǒ zài shàng yǔyán kè.","I'm taking a language class."],
  ["她是一个志愿者。","Tā shì yí ge zhìyuànzhě.","She is a volunteer."],
  ["你可以尝试打招呼。","Nǐ kěyǐ chángshì dǎ zhāohu.","You can try saying hello."],
  ["他向我打招呼。","Tā xiàng wǒ dǎ zhāohu.","He greeted me."],
  ["当地人很友好。","Dāngdì rén hěn yǒuhǎo.","The local people are friendly."],
  ["这里的人很友好。","Zhèlǐ de rén hěn yǒuhǎo.","People here are very friendly."],
  ["刚到新城市时我很想家。","Gāng dào xīn chéngshì shí wǒ hěn xiǎngjiā.","When I first arrived in the new city I was homesick."],
  ["清迈有很多山。","Qīngmài yǒu hěn duō shān.","Chiang Mai has many mountains."],
  ["这里有美丽的森林。","Zhèlǐ yǒu měilì de sēnlín.","There are beautiful forests here."],
  ["谢谢你的帮助。","Xièxie nǐ de bāngzhù.","Thank you for your help."],
  ["每个人的幸福都不一样。","Měi ge rén de xìngfú dōu bù yíyàng.","Everyone's happiness is different."],
  ["清迈的安静很吸引我。","Qīngmài de ānjìng hěn xīyǐn wǒ.","Chiang Mai's quiet really attracts me."],
  ["我在越南旅居过。","Wǒ zài Yuènán lǚjū guò.","I have lived in Vietnam."],
  ["住在国外不容易。","Zhù zài guówài bù róngyì.","Living abroad is not easy."],
  ["周末我喜欢去购物。","Zhōumò wǒ xǐhuan qù gòuwù.","I like to go shopping on weekends."],
  ["这条裙子在打折。","Zhè tiáo qúnzi zài dǎzhé.","This skirt is on sale."],
  ["我可以试一下吗？","Wǒ kěyǐ shì yíxià ma?","Can I try it on?"],
  ["试衣间在那边。","Shìyījiān zài nà biān.","The fitting room is over there."],
  ["当然可以。","Dāngrán kěyǐ.","Of course you can."],
  ["你穿什么号？","Nǐ chuān shénme hào?","What size do you wear?"],
  ["能便宜一点儿吗？","Néng piányi yìdiǎnr ma?","Can it be a little cheaper?"],
  ["这件衣服太贵了。","Zhè jiàn yīfu tài guì le.","This is too expensive."],
  ["这个多少钱？","Zhège duōshao qián?","How much is this?"],
  ["这件怎么样？","Zhè jiàn zěnmeyàng?","How about this one?"],
  ["我想买新衣服。","Wǒ xiǎng mǎi xīn yīfu.","I want to buy new clothes."],
  ["她穿了一条红裙子。","Tā chuān le yì tiáo hóng qúnzi.","She wore a red skirt."],
  ["这条裤子有点长。","Zhè tiáo kùzi yǒudiǎn cháng.","These trousers are a bit long."],
  ["我喜欢这件衬衫。","Wǒ xǐhuan zhè jiàn chènshān.","I like this shirt."],
  ["这双鞋很好看。","Zhè shuāng xié hěn hǎokàn.","These shoes look nice."],
  ["小号卖完了。","Xiǎohào màiwán le.","The small size is sold out."],
  ["我用手机支付。","Wǒ yòng shǒujī zhīfù.","I pay with my phone."],
  ["可以用信用卡吗？","Kěyǐ yòng xìnyòngkǎ ma?","Can I use a credit card?"],
  ["这是给你的礼物。","Zhè shì gěi nǐ de lǐwù.","This is a gift for you."],
  ["我想寄一张明信片。","Wǒ xiǎng jì yì zhāng míngxìnpiàn.","I want to mail a postcard."],
  ["我买了一张明信片。","Wǒ mǎi le yì zhāng míngxìnpiàn.","I bought a postcard."],
  ["我喜欢买纪念品。","Wǒ xǐhuan mǎi jìniànpǐn.","I like buying souvenirs."],
  ["我想租一个房子。","Wǒ xiǎng zū yí ge fángzi.","I want to rent a house."],
  ["这个房子可以租吗？","Zhège fángzi kěyǐ zū ma?","Can this house be rented?"],
  ["租金一个月多少钱？","Zūjīn yí ge yuè duōshao qián?","How much is the monthly rent?"],
  ["我找中介看房子。","Wǒ zhǎo zhōngjiè kàn fángzi.","I get an agent to view houses."],
  ["这个房子很合适。","Zhège fángzi hěn héshì.","This house is very suitable."],
  ["这里的位置很好。","Zhèlǐ de wèizhi hěn hǎo.","The location here is good."],
  ["厨房很大。","Chúfáng hěn dà.","The kitchen is big."],
  ["主卧有一个卫生间。","Zhǔwò yǒu yí ge wèishēngjiān.","The main bedroom has a bathroom."],
  ["这个房子有两个卧室。","Zhège fángzi yǒu liǎng ge wòshì.","This house has two bedrooms."],
  ["客厅很亮。","Kètīng hěn liàng.","The living room is bright."],
  ["我喜欢有阳台的房子。","Wǒ xǐhuan yǒu yángtái de fángzi.","I like houses with a balcony."],
  ["这个房子有家具。","Zhège fángzi yǒu jiāju.","This house is furnished."],
  ["这栋楼没有电梯。","Zhè dòng lóu méiyǒu diàntī.","This building has no elevator."],
  ["这个小区很安静。","Zhège xiǎoqū hěn ānjìng.","This residential area is quiet."],
  ["房东人很好。","Fángdōng rén hěn hǎo.","The landlord is nice."],
  ["卧室朝南，阳光很好。","Wòshì cháonán, yángguāng hěn hǎo.","The bedroom faces south, with good sunlight."],
  ["因为下雨，我没出去。","Yīnwèi xiàyǔ, wǒ méi chūqu.","Because it rained, I didn't go out."],
  ["房子很贵，所以我没租。","Fángzi hěn guì, suǒyǐ wǒ méi zū.","The house was expensive, so I didn't rent it."],
  ["要是便宜一点就好了。","Yàoshì piányi yìdiǎn jiù hǎo le.","It would be great if it were a bit cheaper."],
  ["下个月我要搬家。","Xià ge yuè wǒ yào bānjiā.","I'm moving next month."],
  ["我对这个房子很满意。","Wǒ duì zhège fángzi hěn mǎnyì.","I'm very satisfied with this house."],
  ["房东不同意养宠物。","Fángdōng bù tóngyì yǎng chǒngwù.","The landlord doesn't allow pets."],
  ["今天天气很好。","Jīntiān tiānqì hěn hǎo.","The weather is nice today."],
  ["我最喜欢的季节是秋天。","Wǒ zuì xǐhuan de jìjié shì qiūtiān.","My favorite season is autumn."],
  ["春天很暖和。","Chūntiān hěn nuǎnhuo.","Spring is warm."],
  ["夏天很热。","Xiàtiān hěn rè.","Summer is hot."],
  ["秋天很凉快。","Qiūtiān hěn liángkuai.","Autumn is cool."],
  ["冬天常常下雪。","Dōngtiān chángcháng xiàxuě.","It often snows in winter."],
  ["今天很暖和。","Jīntiān hěn nuǎnhuo.","It's warm today."],
  ["外面很热。","Wàimiàn hěn rè.","It's hot outside."],
  ["冬天很冷。","Dōngtiān hěn lěng.","Winter is cold."],
  ["秋天的天气很凉快。","Qiūtiān de tiānqì hěn liángkuai.","Autumn weather is cool."],
  ["今天是晴天。","Jīntiān shì qíngtiān.","Today is sunny."],
  ["天阴了。","Tiān yīn le.","It's gotten cloudy."],
  ["明天多云。","Míngtiān duōyún.","Tomorrow is cloudy."],
  ["外面在刮风。","Wàimiàn zài guāfēng.","It's windy outside."],
  ["下雨了。","Xiàyǔ le.","It's raining."],
  ["冬天这里下雪。","Dōngtiān zhèlǐ xiàxuě.","It snows here in winter."],
  ["今天二十五度。","Jīntiān èrshíwǔ dù.","It's 25 degrees today."],
  ["明天零下五度。","Míngtiān língxià wǔ dù.","Tomorrow is minus five degrees."],
  ["天气预报说明天下雨。","Tiānqì yùbào shuō míngtiān xiàyǔ.","The forecast says it will rain tomorrow."],
  ["天气预报一点儿也不准。","Tiānqì yùbào yìdiǎnr yě bù zhǔn.","The forecast isn't accurate at all."],
  ["记得带伞。","Jìde dài sǎn.","Remember to bring an umbrella."],
  ["现在是雨季。","Xiànzài shì yǔjì.","It's the rainy season now."],
  ["泰国有旱季和雨季。","Tàiguó yǒu hànjì hé yǔjì.","Thailand has a dry and a rainy season."],
  ["南方的冬天不太冷。","Nánfāng de dōngtiān bú tài lěng.","Winters in the south aren't very cold."],
  ["北方的冬天很冷。","Běifāng de dōngtiān hěn lěng.","Winters in the north are very cold."],
  ["夏天我喜欢游泳。","Xiàtiān wǒ xǐhuan yóuyǒng.","I like swimming in summer."],
  ["冬天我们去滑雪。","Dōngtiān wǒmen qù huáxuě.","We go skiing in winter."],
  ["春天我们去野餐。","Chūntiān wǒmen qù yěcān.","We go for a picnic in spring."],
  ["晚饭后我去散步。","Wǎnfàn hòu wǒ qù sànbù.","I take a walk after dinner."],
  ["他生病了。","Tā shēngbìng le.","He got sick."],
  ["我感冒了。","Wǒ gǎnmào le.","I caught a cold."],
  ["我一直咳嗽。","Wǒ yìzhí késou.","I keep coughing."],
  ["我有点发烧。","Wǒ yǒudiǎn fāshāo.","I have a slight fever."],
  ["我一直打喷嚏。","Wǒ yìzhí dǎ pēntì.","I keep sneezing."],
  ["我流鼻涕。","Wǒ liú bítì.","I have a runny nose."],
  ["我头疼。","Wǒ tóu téng.","I have a headache."],
  ["我嗓子很疼。","Wǒ sǎngzi hěn téng.","My throat really hurts."],
  ["他肚子疼。","Tā dùzi téng.","He has a stomachache."],
  ["我的头很疼。","Wǒ de tóu hěn téng.","My head hurts a lot."],
  ["别忘了吃药。","Bié wàng le chī yào.","Don't forget to take your medicine."],
  ["你吃药了吗？","Nǐ chī yào le ma?","Did you take your medicine?"],
  ["药店在一楼。","Yàodiàn zài yī lóu.","The pharmacy is on the first floor."],
  ["你去过医院了吗？","Nǐ qù guò yīyuàn le ma?","Have you been to the hospital?"],
  ["医生给我开了药。","Yīshēng gěi wǒ kāi le yào.","The doctor prescribed me medicine."],
  ["我对芒果过敏。","Wǒ duì mángguǒ guòmǐn.","I'm allergic to mango."],
  ["一次吃两片。","Yí cì chī liǎng piàn.","Take two tablets each time."],
  ["一天三次。","Yì tiān sān cì.","Three times a day."],
  ["饭后吃药。","Fàn hòu chī yào.","Take the medicine after meals."],
  ["睡前吃一片。","Shuì qián chī yí piàn.","Take one tablet before bed."],
  ["我喜欢远程工作。","Wǒ xǐhuan yuǎnchéng gōngzuò.","I like remote work."],
  ["我不用去办公室。","Wǒ búyòng qù bàngōngshì.","I don't need to go to the office."],
  ["我用电脑工作。","Wǒ yòng diànnǎo gōngzuò.","I work on a computer."],
  ["这里的网络很好。","Zhèlǐ de wǎngluò hěn hǎo.","The internet here is good."],
  ["我和同事一起吃午饭。","Wǒ hé tóngshì yìqǐ chī wǔfàn.","I have lunch with my colleagues."],
  ["我们一起吃午饭。","Wǒmen yìqǐ chī wǔfàn.","We have lunch together."],
  ["一个人工作有点孤独。","Yí ge rén gōngzuò yǒudiǎn gūdú.","Working alone is a bit lonely."],
  ["在家工作容易分心。","Zàijiā gōngzuò róngyì fēnxīn.","It's easy to get distracted working at home."],
  ["怎么解决这个问题？","Zěnme jiějué zhège wèntí?","How do we solve this problem?"],
  ["我安排好了时间。","Wǒ ānpái hǎo le shíjiān.","I've arranged my time."],
  ["这种工作方式很自由。","Zhè zhǒng gōngzuò fāngshì hěn zìyóu.","This way of working is very free."],
  ["远程工作很自由。","Yuǎnchéng gōngzuò hěn zìyóu.","Remote work is very free."],
  ["工作有一些困难。","Gōngzuò yǒu yìxiē kùnnan.","Work has some difficulties."],
  ["我想体验新的文化。","Wǒ xiǎng tǐyàn xīn de wénhuà.","I want to experience new cultures."],
  ["房间里有一张桌子。","Fángjiān lǐ yǒu yì zhāng zhuōzi.","There's a table in the room."],
  ["他做自由职业。","Tā zuò zìyóu zhíyè.","He's a freelancer."],
  ["他想回公司上班。","Tā xiǎng huí gōngsī shàngbān.","He wants to go back to work at a company."],
  ["他是自己的老板。","Tā shì zìjǐ de lǎobǎn.","He's his own boss."],
  ["客户给的钱变少了。","Kèhù gěi de qián biàn shǎo le.","Clients are paying less."],
  ["我压力很大。","Wǒ yālì hěn dà.","I'm under a lot of stress."],
  ["别担心。","Bié dānxīn.","Don't worry."],
  ["我把假期推迟了。","Wǒ bǎ jiàqī tuīchí le.","I postponed my holiday."],
  ["会议推迟了。","Huìyì tuīchí le.","The meeting was postponed."],
  ["开咖啡店不太赚钱。","Kāi kāfēidiàn bú tài zhuànqián.","Running a café doesn't make much money."],
  ["东西越来越贵。","Dōngxi yuèláiyuè guì.","Things are getting more and more expensive."],
  ["这是个好主意。","Zhè shì ge hǎo zhǔyi.","That's a good idea."],
  ["我有一些存款。","Wǒ yǒu yìxiē cúnkuǎn.","I have some savings."],
  ["他认真想过这件事。","Tā rènzhēn xiǎng guò zhè jiàn shì.","He has seriously thought about it."],
  ["公司做了一个调查。","Gōngsī zuò le yí ge diàochá.","The company did a survey."],
  ["他可能要去约会。","Tā kěnéng yào qù yuēhuì.","He's probably going on a date."],
  ["你有什么爱好？","Nǐ yǒu shénme àihào?","What hobbies do you have?"],
  ["我对摄影很感兴趣。","Wǒ duì shèyǐng hěn gǎn xìngqù.","I'm very interested in photography."],
  ["我喜欢做饭。","Wǒ xǐhuan zuòfàn.","I like cooking."],
  ["爷爷喜欢下棋。","Yéye xǐhuan xiàqí.","Grandpa likes playing chess."],
  ["她很喜欢跳舞。","Tā hěn xǐhuan tiàowǔ.","She loves dancing."],
  ["我每天做运动。","Wǒ měitiān zuò yùndòng.","I exercise every day."],
  ["我常去健身房。","Wǒ cháng qù jiànshēnfáng.","I often go to the gym."],
  ["我们去打羽毛球吧。","Wǒmen qù dǎ yǔmáoqiú ba.","Let's go play badminton."],
  ["攀岩很有意思。","Pānyán hěn yǒu yìsi.","Rock climbing is fun."],
  ["我想试试射箭。","Wǒ xiǎng shìshi shèjiàn.","I want to try archery."],
  ["摄影是我的爱好。","Shèyǐng shì wǒ de àihào.","Photography is my hobby."],
  ["我们去听音乐会。","Wǒmen qù tīng yīnyuèhuì.","We're going to a concert."],
  ["他在学编程。","Tā zài xué biānchéng.","He's learning programming."],
  ["很多老年人喜欢散步。","Hěn duō lǎoniánrén xǐhuan sànbù.","Many elderly people like to walk."],
  ["我们的爱好相同。","Wǒmen de àihào xiāngtóng.","We have the same hobbies."],
  ["我家离公园很近。","Wǒ jiā lí gōngyuán hěn jìn.","My home is close to the park."],
  ["地铁站离这儿很近。","Dìtiě zhàn lí zhèr hěn jìn.","The subway station is near here."],
  ["你家离公司远吗？","Nǐ jiā lí gōngsī yuǎn ma?","Is your home far from the office?"],
  ["离这儿大概两公里。","Lí zhèr dàgài liǎng gōnglǐ.","It's about two kilometers from here."],
  ["在这站换乘二号线。","Zài zhè zhàn huànchéng èr hào xiàn.","Transfer to Line 2 at this stop."],
  ["你一直往前走。","Nǐ yìzhí wǎng qián zǒu.","Keep walking straight ahead."],
  ["我是坐飞机来的。","Wǒ shì zuò fēijī lái de.","I came by plane."],
  ["我们坐火车去。","Wǒmen zuò huǒchē qù.","We go by train."],
  ["坐高铁很快。","Zuò gāotiě hěn kuài.","The high-speed rail is fast."],
  ["我们坐船去岛上。","Wǒmen zuò chuán qù dǎo shàng.","We take a boat to the island."],
  ["我坐公共汽车上班。","Wǒ zuò gōnggòng qìchē shàngbān.","I take the bus to work."]
];
