const LESSON_SPEC = [
  ["Appearance & personality", 61],
  ["Time & everyday words", 9],
  ["School & daily life", 30],
  ["City life · Bangkok & Chiang Mai I", 66],
  ["Living abroad · Bangkok & Chiang Mai II", 66],
  ["Shopping 购物", 22],
  ["House hunting 看房子", 22],
  ["Weather & seasons 天气", 29],
  ["Getting sick 生病", 20],
  ["Remote work 远程工作", 15],
  ["Freelance & work 自由职业", 15],
  ["Hobbies & exercise 爱好", 15],
  ["Directions & transport 交通", 16],
  ["Cooking & food 做菜", 24],
  ["Common words & connectors 常用词", 15],
  ["Extras 补充", 2],
  ["Clothing & accessories 穿戴", 18],
  ["Cooking tools & extras 厨具", 18],
  ["Transport & tickets 交通2", 15],
  ["Home & furniture 家里", 18],
  ["Habits & routines 习惯", 14],
  ["Grammar & daily life · 入乡随俗", 18],
  ["Hometown · city vs. countryside 家乡", 36],
  ["入乡随俗 · When in Rome", 41],
  ["我和中国有个约会 · A date with China", 25],
  ["我和中国有个约会 II · 其实 & reading", 37],
  ["我这里一切都好 · 当 & 越……越……", 28],
  ["我这里一切都好 II · Mom's email 邮件", 35],
  ["我这里一切都好 III · Reply to Mom 回信", 31]
];
