// Confusable pairs: two words learners mix up, a one-line note on the difference,
// and one sentence per word where ONLY that word fits. [zh, pinyin, en] like the examples.
// Format: [wordA, wordB, note, [sentence that needs A], [sentence that needs B]]
const PAIRS = [
  ["买","卖","买 mǎi = buy (3rd tone, 'no money yet'). 卖 mài = sell (4th tone, with 十 on top: 'ten things to sell').",
    ["我想＿＿一个新手机。","Wǒ xiǎng mǎi yí ge xīn shǒujī.","I want to buy a new phone."],
    ["这家店＿＿水果。","Zhè jiā diàn mài shuǐguǒ.","This shop sells fruit."]],
  ["戴","带","戴 dài = wear on the body (glasses, hat, watch, ring). 带 dài = bring / take along / lead.",
    ["他＿＿着一副眼镜。","Tā dàizhe yí fù yǎnjìng.","He is wearing glasses."],
    ["别忘了＿＿伞。","Bié wàng le dài sǎn.","Don't forget to bring an umbrella."]],
  ["穿","戴","穿 chuān = wear clothes and shoes (things you put your body into). 戴 dài = wear accessories (things you put on).",
    ["今天很冷，＿＿上外套。","Jīntiān hěn lěng, chuān shàng wàitào.","It's cold today, put on a coat."],
    ["冬天我喜欢＿＿围巾。","Dōngtiān wǒ xǐhuan dài wéijīn.","In winter I like wearing a scarf."]],
  ["适合","合适","适合 shìhé is a verb: A 适合 B (suits). 合适 héshì is an adjective: 很合适 (suitable). Never 很适合 + nothing.",
    ["这个城市＿＿内向的人。","Zhège chéngshì shìhé nèixiàng de rén.","This city suits introverted people."],
    ["这个房子很＿＿。","Zhège fángzi hěn héshì.","This house is very suitable."]],
  ["感觉","感受","感觉 gǎnjué = a feeling / to feel (physical or quick impression). 感受 gǎnshòu = to experience deeply, take in.",
    ["我＿＿有点儿冷。","Wǒ gǎnjué yǒudiǎnr lěng.","I feel a bit cold."],
    ["慢慢＿＿这里的生活。","Mànmàn gǎnshòu zhèlǐ de shēnghuó.","Slowly take in life here."]],
  ["认识","知道","认识 rènshi = know a person / recognise a character. 知道 zhīdào = know a fact.",
    ["我不＿＿他，但是听说过他。","Wǒ bú rènshi tā, dànshì tīngshuō guo tā.","I don't know him personally, but I've heard of him."],
    ["你＿＿他几点来吗？","Nǐ zhīdào tā jǐ diǎn lái ma?","Do you know what time he's coming?"]],
  ["想","想念","想 xiǎng = miss (casual), also think / want. 想念 xiǎngniàn = miss, deeper and more formal, people or places.",
    ["我＿＿吃饺子。","Wǒ xiǎng chī jiǎozi.","I want to eat dumplings."],
    ["住在国外，我很＿＿家乡。","Zhù zài guówài, wǒ hěn xiǎngniàn jiāxiāng.","Living abroad, I miss my hometown a lot."]],
  ["看法","想法","看法 kànfǎ = opinion / view ON something. 想法 xiǎngfǎ = idea / thought you came up with.",
    ["你对这件事有什么＿＿？","Nǐ duì zhè jiàn shì yǒu shénme kànfǎ?","What's your view on this matter?"],
    ["我有一个好＿＿：我们去爬山吧！","Wǒ yǒu yí ge hǎo xiǎngfǎ: wǒmen qù páshān ba!","I have a good idea: let's go hiking!"]],
  ["再","又","再 zài = again in the FUTURE (not yet happened). 又 yòu = again in the PAST (already happened).",
    ["明天＿＿来吧。","Míngtiān zài lái ba.","Come again tomorrow."],
    ["他昨天＿＿迟到了。","Tā zuótiān yòu chídào le.","He was late again yesterday."]],
  ["然后","后来","然后 ránhòu = then, next step in a sequence (any tense). 后来 hòulái = later on, only for the past.",
    ["先洗手，＿＿吃饭。","Xiān xǐ shǒu, ránhòu chīfàn.","Wash your hands first, then eat."],
    ["我们以前是同事，＿＿成了朋友。","Wǒmen yǐqián shì tóngshì, hòulái chéng le péngyou.","We used to be colleagues; later we became friends."]],
  ["以后","之后","以后 yǐhòu can stand alone: 以后再说 'later'. 之后 zhīhòu needs something before it: 下班之后.",
    ["＿＿再说吧。","Yǐhòu zài shuō ba.","Let's talk about it later."],
    ["吃饭＿＿我去散步。","Chīfàn zhīhòu wǒ qù sànbù.","After eating I go for a walk."]],
  ["时间","时候","时间 shíjiān = time as a quantity (have time, spend time). 时候 shíhou = a point in time: ……的时候 'when'.",
    ["我今天没有＿＿。","Wǒ jīntiān méiyǒu shíjiān.","I don't have time today."],
    ["下雨的＿＿我喜欢看书。","Xiàyǔ de shíhou wǒ xǐhuan kàn shū.","When it rains I like to read."]],
  ["懂","明白","懂 dǒng = understand (language, a subject): 听不懂, 看不懂. 明白 míngbai = get it, see the point, clear.",
    ["他说得太快，我听不＿＿。","Tā shuō de tài kuài, wǒ tīng bu dǒng.","He speaks too fast, I can't understand."],
    ["我＿＿你的意思了。","Wǒ míngbai nǐ de yìsi le.","I see what you mean now."]],
  ["记得","记住","记得 jìde = remember (still have in memory). 记住 jìzhù = memorise, fix it in memory.",
    ["你还＿＿我吗？","Nǐ hái jìde wǒ ma?","Do you still remember me?"],
    ["这个词很重要，请＿＿。","Zhège cí hěn zhòngyào, qǐng jìzhù.","This word is important, please memorise it."]],
  ["学习","学会","学习 xuéxí = study (the process). 学会 xuéhuì = learn successfully, master (the result).",
    ["我每天＿＿两个小时。","Wǒ měitiān xuéxí liǎng ge xiǎoshí.","I study two hours every day."],
    ["我终于＿＿了游泳。","Wǒ zhōngyú xuéhuì le yóuyǒng.","I finally learned how to swim."]],
  ["变","变化","变 biàn = verb, to change / become: 变少, 变冷. 变化 biànhuà = noun, a change: 有变化.",
    ["天气＿＿冷了。","Tiānqì biàn lěng le.","The weather has turned cold."],
    ["这个城市有很大的＿＿。","Zhège chéngshì yǒu hěn dà de biànhuà.","This city has changed a lot."]],
  ["改变","换","改变 gǎibiàn = change in nature (a plan, a view, a habit). 换 huàn = swap one thing for another (job, clothes, money).",
    ["他＿＿了自己的看法。","Tā gǎibiàn le zìjǐ de kànfǎ.","He changed his opinion."],
    ["我想＿＿一件大一点儿的。","Wǒ xiǎng huàn yí jiàn dà yìdiǎnr de.","I'd like to exchange it for a bigger one."]],
  ["简单","容易","简单 jiǎndān = simple, not complicated (structure). 容易 róngyì = easy to do (effort).",
    ["这个菜很＿＿，只要三种调料。","Zhège cài hěn jiǎndān, zhǐyào sān zhǒng tiáoliào.","This dish is simple, it only needs three seasonings."],
    ["学汉语不＿＿。","Xué Hànyǔ bù róngyì.","Learning Chinese isn't easy."]],
  ["虽然","尽管","Both = although, but 尽管 jǐnguǎn is stronger and more formal; 虽然 suīrán is the everyday one. Both pair with 但是 / 还是.",
    ["＿＿很贵，但是我很喜欢。","Suīrán hěn guì, dànshì wǒ hěn xǐhuan.","Although it's expensive, I like it a lot."],
    ["＿＿下着大雨，他还是来了。","Jǐnguǎn xiàzhe dàyǔ, tā háishi lái le.","Even though it was pouring, he still came."]],
  ["为了","因为","为了 wèile = in order to (purpose, looks forward). 因为 yīnwèi = because (reason, looks back).",
    ["＿＿学好汉语，我每天听录音。","Wèile xuéhǎo Hànyǔ, wǒ měitiān tīng lùyīn.","In order to learn Chinese well, I listen to recordings every day."],
    ["＿＿下雨，比赛取消了。","Yīnwèi xiàyǔ, bǐsài qǔxiāo le.","Because of the rain, the match was cancelled."]],
  ["每天","平时","每天 měitiān = every single day. 平时 píngshí = usually / normally, as opposed to special occasions.",
    ["我＿＿七点起床。","Wǒ měitiān qī diǎn qǐchuáng.","I get up at seven every day."],
    ["我＿＿不喝酒，今天是例外。","Wǒ píngshí bù hē jiǔ, jīntiān shì lìwài.","I don't usually drink; today is an exception."]],
  ["渐渐","越来越","渐渐 jiànjiàn = gradually (adverb before a verb). 越来越 yuèláiyuè = more and more (before an adjective or 喜欢/想).",
    ["天＿＿黑了。","Tiān jiànjiàn hēi le.","It's gradually getting dark."],
    ["东西＿＿贵。","Dōngxi yuèláiyuè guì.","Things are getting more and more expensive."]],
  ["差不多","大概","差不多 chàbuduō = almost / about the same. 大概 dàgài = probably / roughly, a guess about a number or likelihood.",
    ["这两个词的意思＿＿。","Zhè liǎng ge cí de yìsi chàbuduō.","These two words mean about the same."],
    ["他＿＿三十岁。","Tā dàgài sānshí suì.","He's probably about thirty."]],
  ["花","用","花 huā = spend time or money. 用 yòng = use a tool, a language, a method.",
    ["我＿＿了一百块。","Wǒ huā le yì bǎi kuài.","I spent a hundred kuai."],
    ["我们＿＿汉语聊天。","Wǒmen yòng Hànyǔ liáotiān.","We chat in Chinese."]],
  ["该","应该","该 gāi = it's time to (often 该……了). 应该 yīnggāi = should / ought to, advice or probability.",
    ["十二点了，＿＿睡觉了。","Shí'èr diǎn le, gāi shuìjiào le.","It's twelve, time to sleep."],
    ["你＿＿多喝水。","Nǐ yīnggāi duō hē shuǐ.","You should drink more water."]],
  ["离开","出去","离开 líkāi = leave a place or person (for good or for a while). 出去 chūqù = go out / step outside.",
    ["他去年＿＿了北京。","Tā qùnián líkāi le Běijīng.","He left Beijing last year."],
    ["外面天气好，我们＿＿走走吧。","Wàimiàn tiānqì hǎo, wǒmen chūqù zǒuzou ba.","The weather's nice, let's go out for a walk."]],
  ["对不起","不好意思","对不起 duìbuqǐ = sorry, a real apology. 不好意思 bù hǎoyìsi = excuse me / embarrassed, for small things.",
    ["＿＿，我把你的杯子打破了。","Duìbuqǐ, wǒ bǎ nǐ de bēizi dǎpò le.","Sorry, I broke your cup."],
    ["＿＿，请问洗手间在哪儿？","Bù hǎoyìsi, qǐngwèn xǐshǒujiān zài nǎr?","Excuse me, where is the restroom?"]],
  ["热闹","吵","热闹 rènao = lively, bustling (positive). 吵 chǎo = noisy (negative).",
    ["春节的时候街上很＿＿。","Chūnjié de shíhou jiē shàng hěn rènao.","At Spring Festival the streets are lively."],
    ["楼上太＿＿了，我睡不着。","Lóushàng tài chǎo le, wǒ shuì bu zháo.","Upstairs is too noisy, I can't sleep."]],
  ["安静","平静","安静 ānjìng = quiet (a place, a person). 平静 píngjìng = calm (a mood, the sea).",
    ["图书馆里很＿＿。","Túshūguǎn lǐ hěn ānjìng.","It's quiet in the library."],
    ["听了这个消息，他很＿＿。","Tīng le zhège xiāoxi, tā hěn píngjìng.","He stayed calm on hearing the news."]],
  ["漂亮","美丽","漂亮 piàoliang = pretty, everyday word for people and things. 美丽 měilì = beautiful, more literary: scenery, a city, a story.",
    ["她今天穿得真＿＿。","Tā jīntiān chuān de zhēn piàoliang.","She's dressed really prettily today."],
    ["这是一个＿＿的传说。","Zhè shì yí ge měilì de chuánshuō.","This is a beautiful legend."]],
  ["快乐","幸福","快乐 kuàilè = happy, joyful in the moment (生日快乐). 幸福 xìngfú = happiness in life, wellbeing.",
    ["生日＿＿！","Shēngrì kuàilè!","Happy birthday!"],
    ["有家人在身边，我觉得很＿＿。","Yǒu jiārén zài shēnbiān, wǒ juéde hěn xìngfú.","With family around me, I feel truly happy."]],
  ["工作","上班","工作 gōngzuò = a job / to work (in general). 上班 shàngbān = go to work, be at work (the daily act).",
    ["你做什么＿＿？","Nǐ zuò shénme gōngzuò?","What do you do for work?"],
    ["我每天九点＿＿。","Wǒ měitiān jiǔ diǎn shàngbān.","I start work at nine every day."]],
  ["一般","通常","一般 yìbān = usually, and also 'so-so / ordinary' as an adjective. 通常 tōngcháng = usually, only an adverb.",
    ["这家餐厅的菜很＿＿。","Zhè jiā cāntīng de cài hěn yìbān.","The food at this restaurant is so-so."],
    ["我＿＿坐地铁上班。","Wǒ tōngcháng zuò dìtiě shàngbān.","I usually take the subway to work."]],
  ["预习","复习","预习 yùxí = preview BEFORE class (预 = in advance). 复习 fùxí = review AFTER class (复 = again).",
    ["上课以前要＿＿新课。","Shàngkè yǐqián yào yùxí xīn kè.","Before class you should preview the new lesson."],
    ["考试以前要＿＿。","Kǎoshì yǐqián yào fùxí.","Before the exam you should review."]],
  ["地方","位置","地方 dìfang = a place (general). 位置 wèizhi = a position / location, where exactly something sits.",
    ["这是一个很漂亮的＿＿。","Zhè shì yí ge hěn piàoliang de dìfang.","This is a beautiful place."],
    ["这家店的＿＿很好，就在地铁站旁边。","Zhè jiā diàn de wèizhi hěn hǎo, jiù zài dìtiězhàn pángbiān.","The shop's location is great, right next to the subway."]]
];
