// 多音字 — characters with more than one reading. [reading, meaning, example word]
// The app works out which reading a word uses from its pinyin and shows the others on the card.
const POLY = {
  "背": [["bèi","back / to recite / behind","背后"],["bēi","to carry on the back","背包"]],
  "便": [["biàn","convenient / then","方便"],["pián","(in 便宜 cheap)","便宜"]],
  "参": [["cān","to join / take part","参加"],["shēn","ginseng","人参"]],
  "藏": [["cáng","to hide","收藏"],["zàng","Tibet","西藏"]],
  "差": [["chà","bad / lacking / differ","差不多"],["chā","difference","时差"],["chāi","errand","出差"]],
  "场": [["chǎng","place / field","商场"],["cháng","measure word for events (rain, illness)","一场雨"]],
  "朝": [["cháo","dynasty / facing","朝南"],["zhāo","morning","朝阳"]],
  "称": [["chēng","to call / to weigh","称呼"],["chèn","to suit / fit","称心"]],
  "处": [["chù","place / office","到处"],["chǔ","to deal with / get along","相处"]],
  "传": [["chuán","to pass on / spread","传统"],["zhuàn","biography","自传"]],
  "答": [["dá","to answer","回答"],["dā","(in 答应 to agree)","答应"]],
  "打": [["dǎ","to hit / play / make","打电话"],["dá","dozen","一打"]],
  "大": [["dà","big","大学"],["dài","(in 大夫 doctor)","大夫"]],
  "待": [["dài","to treat / wait for","待遇"],["dāi","to stay","待在家"]],
  "单": [["dān","single / list / simple","简单"],["shàn","(surname)","单"]],
  "担": [["dān","to carry / shoulder","担心"],["dàn","load / burden","重担"]],
  "弹": [["tán","to play (an instrument) / flick","弹钢琴"],["dàn","bullet","子弹"]],
  "当": [["dāng","to be / when","当然"],["dàng","proper / to treat as","上当"]],
  "倒": [["dǎo","to fall over","摔倒"],["dào","to pour / upside down / yet","倒是"]],
  "得": [["de","(links a verb to its result)","说得好"],["dé","to get","得到"],["děi","must","得去"]],
  "地": [["de","(makes an adverb)","慢慢地"],["dì","ground / place","地方"]],
  "的": [["de","(possessive / attributive)","我的"],["dí","truly (的确)","的确"],["dì","target","目的"]],
  "调": [["tiáo","to adjust / mix","调整"],["diào","tune / to transfer","声调"]],
  "都": [["dōu","all","都是"],["dū","capital city","首都"]],
  "发": [["fā","to send out / develop","发现"],["fà","hair","头发"]],
  "分": [["fēn","to divide / minute / cent","分钟"],["fèn","component / portion","部分"]],
  "干": [["gān","dry","干净"],["gàn","to do / work","干活"]],
  "给": [["gěi","to give / for","给你"],["jǐ","to supply","供给"]],
  "更": [["gèng","even more","更加"],["gēng","to change / night watch","更新"]],
  "还": [["hái","still / also","还是"],["huán","to return / give back","还钱"]],
  "好": [["hǎo","good","你好"],["hào","to like / be fond of","爱好"]],
  "和": [["hé","and / peace / with","和平"],["huo","(in 暖和 warm)","暖和"]],
  "会": [["huì","can / meeting / a moment","开会"],["kuài","(in 会计 accounting)","会计"]],
  "几": [["jǐ","how many / several","几个"],["jī","small table / nearly","几乎"]],
  "假": [["jiǎ","fake / if","假如"],["jià","holiday","放假"]],
  "间": [["jiān","between / room","中间"],["jiàn","gap / to separate","间接"]],
  "角": [["jiǎo","corner / horn / 10 cents","角落"],["jué","role / actor","角色"]],
  "教": [["jiāo","to teach (verb)","教书"],["jiào","teaching / religion / in compounds","教室"]],
  "结": [["jié","to tie / conclude","结果"],["jiē","to bear fruit / sturdy (结实)","结实"]],
  "尽": [["jǐn","as much as possible","尽管"],["jìn","to exhaust / finish","尽力"]],
  "觉": [["jué","to feel","觉得"],["jiào","sleep","睡觉"]],
  "卡": [["kǎ","card","卡片"],["qiǎ","to get stuck","卡住"]],
  "空": [["kōng","empty / sky","天空"],["kòng","free time / blank","有空"]],
  "乐": [["lè","happy","快乐"],["yuè","music","音乐"]],
  "了": [["le","(completed action)","吃了"],["liǎo","to finish / to be able","受不了"]],
  "累": [["lèi","tired","很累"],["lěi","to accumulate","积累"]],
  "量": [["liàng","quantity","数量"],["liáng","to measure","量体温"]],
  "落": [["luò","to fall / drop","落后"],["là","to leave behind / forget","落在家里"]],
  "吗": [["ma","(question particle)","好吗"],["má","(in 干吗 what for)","干吗"]],
  "没": [["méi","not (have)","没有"],["mò","to sink / submerge","淹没"]],
  "哪": [["nǎ","which","哪里"],["na","(sentence-final particle)","天哪"]],
  "难": [["nán","difficult","难过"],["nàn","disaster","灾难"]],
  "呢": [["ne","(particle)","你呢"],["ní","wool cloth","呢子"]],
  "漂": [["piào","pretty (漂亮)","漂亮"],["piāo","to float","漂流"],["piǎo","to bleach","漂白"]],
  "铺": [["pū","to spread / lay","铺床"],["pù","shop","店铺"]],
  "奇": [["qí","strange / surprising","奇怪"],["jī","odd (number)","奇数"]],
  "强": [["qiáng","strong","强大"],["qiǎng","to force","勉强"],["jiàng","stubborn","倔强"]],
  "切": [["qiē","to cut","切菜"],["qiè","(in 一切 everything)","一切"]],
  "曲": [["qū","bent","弯曲"],["qǔ","song / tune","歌曲"]],
  "散": [["sàn","to scatter / disperse","散步"],["sǎn","loose","松散"]],
  "少": [["shǎo","few","多少"],["shào","young","少年"]],
  "谁": [["shéi","who (spoken)","谁的"],["shuí","who (formal reading)","谁"]],
  "什": [["shén","(in 什么 what)","什么"],["shí","assorted / ten (formal)","什锦"]],
  "省": [["shěng","province / to save","节省"],["xǐng","to reflect / be aware","反省"]],
  "熟": [["shú","ripe / familiar","熟悉"],["shóu","cooked / ripe (spoken)","饭熟了"]],
  "数": [["shù","number","数学"],["shǔ","to count","数一数"]],
  "似": [["sì","similar / seem","似乎"],["shì","(in 似的 like)","似的"]],
  "挑": [["tiāo","to pick / choose","挑选"],["tiǎo","to provoke / poke","挑战"]],
  "为": [["wèi","for / because","因为"],["wéi","to be / to act as","成为"]],
  "系": [["xì","system / department","关系"],["jì","to tie","系鞋带"]],
  "相": [["xiāng","each other","相信"],["xiàng","appearance / photo","照相"]],
  "行": [["xíng","to walk / OK / to travel","旅行"],["háng","row / profession / bank","银行"]],
  "兴": [["xìng","interest / mood","高兴"],["xīng","to rise / flourish","兴奋"]],
  "血": [["xuè","blood (formal / compounds)","血液"],["xiě","blood (spoken)","流血"]],
  "要": [["yào","to want / will / important","需要"],["yāo","to demand","要求"]],
  "应": [["yīng","should","应该"],["yìng","to respond","答应"]],
  "脏": [["zāng","dirty","很脏"],["zàng","internal organ","心脏"]],
  "长": [["cháng","long","长城"],["zhǎng","to grow / chief","长大"]],
  "着": [["zhe","(ongoing action)","看着"],["zháo","to touch / succeed in","睡着"],["zhuó","to wear / apply","着急"],["zhāo","move (in a game)","高着"]],
  "只": [["zhī","measure word for animals / one of a pair","一只猫"],["zhǐ","only","只有"]],
  "中": [["zhōng","middle / China","中国"],["zhòng","to hit the mark / be hit by","中奖"]],
  "种": [["zhǒng","kind / type","种类"],["zhòng","to plant","种树"]],
  "重": [["zhòng","heavy / important","重要"],["chóng","again / repeat","重新"]],
  "转": [["zhuǎn","to turn / change","转弯"],["zhuàn","to revolve / spin","转圈"]]
};
