// Radicals: [radical, pinyin, meaning, variant forms, [[char, pinyin, meaning] x3]]
const RADICALS = [
  ["人","rén","person / man","亻",[["你","nǐ","you"],["他","tā","he"],["休","xiū","to rest"]]],
  ["刀","dāo","knife","刂",[["分","fēn","to divide"],["到","dào","to arrive"],["别","bié","don't / other"]]],
  ["力","lì","power / strength","",[["动","dòng","to move"],["男","nán","male"],["加","jiā","to add"]]],
  ["又","yòu","right hand / again","",[["友","yǒu","friend"],["对","duì","correct"],["双","shuāng","pair"]]],
  ["口","kǒu","mouth","",[["吃","chī","to eat"],["喝","hē","to drink"],["叫","jiào","to call"]]],
  ["囗","wéi","enclosure","",[["国","guó","country"],["园","yuán","garden"],["因","yīn","because"]]],
  ["土","tǔ","earth / soil","",[["地","dì","ground"],["场","chǎng","place / field"],["坐","zuò","to sit"]]],
  ["夕","xī","sunset / evening","",[["多","duō","many"],["外","wài","outside"],["名","míng","name"]]],
  ["大","dà","big / large","",[["天","tiān","sky / day"],["太","tài","too"],["头","tóu","head"]]],
  ["女","nǚ","woman / female","",[["好","hǎo","good"],["妈","mā","mom"],["她","tā","she"]]],
  ["子","zǐ","child / son","",[["学","xué","to study"],["孩","hái","child"],["字","zì","character"]]],
  ["寸","cùn","inch","",[["时","shí","time"],["对","duì","correct"],["寺","sì","temple"]]],
  ["小","xiǎo","small / young","",[["少","shǎo","few"],["尖","jiān","sharp"],["尘","chén","dust"]]],
  ["工","gōng","labor / work","",[["红","hóng","red"],["左","zuǒ","left"],["空","kōng","empty / space"]]],
  ["幺","yāo","tiny","",[["幼","yòu","young"],["乡","xiāng","countryside"],["幻","huàn","illusion"]]],
  ["弓","gōng","bow","",[["张","zhāng","to stretch (mw)"],["弟","dì","younger brother"],["强","qiáng","strong"]]],
  ["心","xīn","heart","忄",[["想","xiǎng","to think"],["忙","máng","busy"],["快","kuài","fast"]]],
  ["戈","gē","dagger-axe","",[["我","wǒ","I / me"],["找","zhǎo","to look for"],["或","huò","or"]]],
  ["手","shǒu","hand","扌",[["打","dǎ","to hit"],["拿","ná","to take"],["换","huàn","to change"]]],
  ["日","rì","sun / day","",[["明","míng","bright"],["早","zǎo","early"],["晴","qíng","sunny"]]],
  ["月","yuè","moon / month","",[["有","yǒu","to have"],["朋","péng","friend"],["服","fú","clothes"]]],
  ["木","mù","wood / tree","",[["林","lín","forest"],["校","xiào","school"],["树","shù","tree"]]],
  ["水","shuǐ","water","氵",[["海","hǎi","sea"],["河","hé","river"],["游","yóu","to swim"]]],
  ["火","huǒ","fire","灬",[["热","rè","hot"],["烤","kǎo","to roast"],["炒","chǎo","to stir-fry"]]],
  ["田","tián","field","",[["男","nán","male"],["累","lèi","tired"],["画","huà","picture"]]],
  ["目","mù","eye","",[["看","kàn","to look"],["眼","yǎn","eye"],["睡","shuì","to sleep"]]],
  ["示","shì","to show / altar","礻",[["祝","zhù","to wish"],["神","shén","spirit / god"],["票","piào","ticket"]]],
  ["糸","mì","fine silk","纟",[["红","hóng","red"],["给","gěi","to give"],["线","xiàn","line / thread"]]],
  ["耳","ěr","ear","",[["听","tīng","to listen"],["取","qǔ","to fetch"],["职","zhí","job"]]],
  ["走","zǒu","to walk","",[["起","qǐ","to rise"],["越","yuè","to exceed"],["趣","qù","interest"]]],
  ["衣","yī","clothing","衤",[["裙","qún","skirt"],["裤","kù","trousers"],["衬","chèn","lining (shirt)"]]],
  ["言","yán","speech","讠",[["说","shuō","to speak"],["语","yǔ","language"],["请","qǐng","please"]]],
  ["贝","bèi","cowry / money","貝",[["贵","guì","expensive"],["费","fèi","fee"],["购","gòu","to buy"]]],
  ["足","zú","foot","",[["跑","pǎo","to run"],["跳","tiào","to jump"],["路","lù","road"]]],
  ["金","jīn","metal / gold","钅",[["钱","qián","money"],["银","yín","silver"],["镜","jìng","mirror / lens"]]],
  ["门","mén","door / gate","門",[["问","wèn","to ask"],["间","jiān","room / between"],["们","men","(plural marker)"]]],
  ["隹","zhuī","short-tailed bird","",[["谁","shéi","who"],["难","nán","difficult"],["售","shòu","to sell"]]],
  ["雨","yǔ","rain","",[["雪","xuě","snow"],["需","xū","to need"],["零","líng","zero"]]],
  ["食","shí","to eat / food","饣",[["饭","fàn","meal"],["饿","è","hungry"],["馆","guǎn","venue / hall"]]],
  ["马","mǎ","horse","馬",[["妈","mā","mom"],["骑","qí","to ride"],["吗","ma","(question particle)"]]]
];

// Rough order of how common each radical is in everyday characters (most common first).
const RAD_ORDER = "口 人 水 手 木 心 言 日 女 土 金 糸 月 火 目 足 走 衣 贝 食 门 雨 大 子 力 刀 又 田 示 耳 小 工 寸 夕 囗 隹 弓 戈 马 幺";

// Which radical each character in the vocabulary is filed under (only the 40 radicals above).
// Each radical card's own example characters are added automatically in app.js.
const RAD_CHARS = {
  "人":"介什休候作偶会仍代全使传化伽假便像偏健伞体做付信位优价值俗但保件他",
  "刀":"到剧别刚利刮前分切刀",
  "力":"动力加助办努功",
  "又":"发受欢变友对",
  "口":"员响只向各商吧古咖啡吵后合呼吸号品台和咳嗽喷嚏嗓吃司味喝史哪唱听告器可虽唐口",
  "囗":"四园国因围困回",
  "土":"城场地堵境域墙坐",
  "夕":"外多名夜舞",
  "大":"头奏天套奇夫太大",
  "女":"好始姜奶如婆姑娘",
  "子":"子学季孤存孩",
  "寸":"寺射导对",
  "小":"尔少尝当小",
  "工":"工差项功",
  "幺":"幽乡",
  "弓":"引",
  "心":"心情性忧息想慢快急忙惯意思感志愿怎念总忆悉懒怪悔怕懂惜您",
  "戈":"戏戴或成戒找",
  "手":"手推拥挤摩托择打招折搬报排担攀摄换接指扮拌挂摆按提挣找扬拿护挺",
  "日":"明早时易是春暖晴旱最普量景晚",
  "月":"胖胡脸朗有服朝期肚脑能背肠腻肥朋望",
  "木":"样棕格校束楼松末术森林梯桌板棋机椒概椅柜村树架极条柿果查榴",
  "水":"海游演流漂深浅活酒浓瀑满泼法泳滑涕汽油洋波清淡济沙冰温潮湿渐汉没消永水",
  "火":"点然热烧照煮煎烤炒炉炖炸灯熬熟火淡",
  "田":"留累由画田",
  "目":"看眼着睡冒真相睛",
  "示":"福礼票祝",
  "糸":"绍红绿继续经结统繁纪络约编终素纯缘系",
  "耳":"聪聊职耳听闻",
  "走":"趣越起超走",
  "衣":"裙裤衬衫袜袋装衣",
  "言":"许课该说论语言试认识记调谢设话谁读诉讨误讲",
  "贝":"购贵赚质资费",
  "足":"路跳跑跟",
  "金":"镜金铁钱锅链钟镇错",
  "门":"闹门间问阅闻",
  "隹":"难谁准",
  "雨":"雨雪零需",
  "食":"馆餐饭饰饱食",
  "马":"骑验驾"
};
