const WORDS = [
  ["海边","hǎibiān","Seaside / Beach"],
  ["推荐","tuījiàn","To recommend"],
  ["通常","tōngcháng","Normally / Usually"],
  ["豆腐","dòufǔ","Tofu"],
  ["游戏","yóuxì","Game"],
  ["介绍","jièshào","To introduce"],
  ["歌手","gēshǒu","Singer"],
  ["演员","yǎnyuán","Actor"],
  ["流行","liúxíng","Pop / Popular"],
  ["心情","xīnqíng","Mood"],
  ["影响","yǐngxiǎng","To affect / Influence"],
  ["只","zhǐ","Only"],
  ["外表","wàibiǎo","Appearance"],
  ["外貌","wàimào","Appearance"],
  ["长什么样","zhǎng shénme yàng","What does someone look like?"],
  ["帅","shuài","Handsome"],
  ["美","měi","Beautiful"],
  ["漂亮","piàoliang","Pretty"],
  ["好看","hǎokàn","Good-looking"],
  ["丑","chǒu","Ugly"],
  ["不好看","bù hǎokàn","Not good-looking"],
  ["高","gāo","Tall"],
  ["矮","ǎi","Short"],
  ["胖","pàng","Fat"],
  ["瘦","shòu","Thin"],
  ["老","lǎo","Old"],
  ["一米八多","yì mǐ bā duō","Over 1.8 meters"],
  ["不到","búdào","Less than / Not quite"],
  ["头发","tóufa","Hair"],
  ["长","cháng","Long"],
  ["短","duǎn","Short"],
  ["卷","juǎn","Curly"],
  ["直","zhí","Straight"],
  ["胡子","húzi","Beard / Mustache"],
  ["留胡子","liú húzi","To grow or keep a beard"],
  ["戴眼镜","dài yǎnjìng","To wear glasses"],
  ["金边眼镜","jīnbiān yǎnjìng","Gold-rimmed glasses"],
  ["脸红","liǎnhóng","To blush"],
  ["颜色","yánsè","Color"],
  ["黑","hēi","Black"],
  ["棕","zōng","Brown"],
  ["金","jīn","Golden"],
  ["红","hóng","Red"],
  ["蓝","lán","Blue"],
  ["绿","lǜ","Green"],
  ["深","shēn","Dark / Deep"],
  ["浅","qiǎn","Light / Shallow"],
  ["性格","xìnggé","Personality"],
  ["外向","wàixiàng","Extroverted"],
  ["开朗","kāilǎng","Cheerful"],
  ["阳光","yángguāng","Sunny / Bright"],
  ["内向","nèixiàng","Introverted"],
  ["安静","ānjìng","Quiet"],
  ["害羞","hàixiū","Shy"],
  ["忧郁","yōuyù","Gloomy"],
  ["e人","e rén","Extrovert (slang)"],
  ["i人","i rén","Introvert (slang)"],
  ["比较","bǐjiào","Relatively / Comparatively"],
  ["聪明","cōngmíng","Smart / Clever"],
  ["幽默","yōumò","Humorous"],
  ["受欢迎","shòu huānyíng","Popular / Well-liked"],
  ["一边……一边……","yī biān … yī biān …","While / at the same time"],
  ["也许","yěxǔ","Maybe / perhaps"],
  ["继续","jìxù","Continue / go on"],
  ["休息","xiūxi","Rest / have a break"],
  ["学习","xuéxí","Study / learn"],
  ["学校","xuéxiào","School"],
  ["发生","fāshēng","Happen / take place"],
  ["已经","yǐjīng","Already"],
  ["结束","jiéshù","End / finish"],
  ["早","zǎo","Early / morning"],
  ["早一点","zǎo yìdiǎn","A little earlier"],
  ["一节课","yì jié kè","One class / a lesson"],
  ["下节课","xià jié kè","The next class"],
  ["逃课","táokè","Skip class"],
  ["数学","shùxué","Math / mathematics"],
  ["人生","rénshēng","Life"],
  ["生活","shēnghuó","Life / to live"],
  ["时候","shíhou","Time / moment"],
  ["什么时候","shénme shíhou","When / what time"],
  ["离开","líkāi","To leave"],
  ["工作","gōngzuò","Work / job"],
  ["有时","yǒushí","Sometimes"],
  ["偶尔","ǒu'ěr","Occasionally"],
  ["经常","jīngcháng","Often"],
  ["等一会","děng yíhuìr","Wait a moment"],
  ["上班","shàngbān","To go to work"],
  ["下班","xiàbān","To get off work"],
  ["仍然","réngrán","Still"],
  ["活动","huódòng","Activity / event"],
  ["电影","diànyǐng","Movie / film"],
  ["电视剧","diànshìjù","TV series"],
  ["想一想","xiǎng yi xiǎng","Think about it"],
  ["不同的","bùtóng de","Different"],
  ["应该","yīnggāi","Should / ought to"],
  ["一定","yídìng","Must / certainly"],
  ["无聊的","wúliáo de","Boring"],
  ["有趣的","yǒuqù de","Interesting / fun"],
  ["简单","jiǎndān","Simple / easy"],
  ["复习","fùxí","Review / go over"],
  ["城市","chéngshì","City"],
  ["著名","zhùmíng","Famous"],
  ["首都","shǒudū","Capital"],
  ["热闹","rènao","Lively / bustling"],
  ["北部","běibù","Northern part"],
  ["节奏","jiézòu","Pace / rhythm"],
  ["慢","màn","Slow"],
  ["各有各的","gè yǒu gè de","Each has its own"],
  ["魅力","mèilì","Charm"],
  ["安全","ānquán","Safe"],
  ["街道","jiēdào","Street"],
  ["现代","xiàndài","Modern"],
  ["楼","lóu","Building / floor"],
  ["商场","shāngchǎng","Shopping mall"],
  ["四通八达","sìtōngbādá","Well-connected / extending everywhere"],
  ["轻轨","qīngguǐ","Light rail"],
  ["地铁","dìtiě","Subway"],
  ["夜生活","yèshēnghuó","Nightlife"],
  ["丰富","fēngfù","Rich / abundant"],
  ["酒吧","jiǔbā","Bar"],
  ["夜市","yèshì","Night market"],
  ["即使","jíshǐ","Even if"],
  ["特别","tèbié","Especially / special"],
  ["拥挤","yōngjǐ","Crowded"],
  ["公园","gōngyuán","Park"],
  ["总的来说","zǒng de lái shuō","Generally speaking"],
  ["快","kuài","Fast"],
  ["交通","jiāotōng","Traffic / transport"],
  ["堵","dǔ","Congested / jammed"],
  ["快乐","kuàilè","Happy"],
  ["完全","wánquán","Completely"],
  ["骑","qí","To ride"],
  ["自行车","zìxíngchē","Bicycle"],
  ["或者","huòzhě","Or"],
  ["走路","zǒulù","To walk"],
  ["古老","gǔlǎo","Ancient"],
  ["寺庙","sìmiào","Temple"],
  ["传统","chuántǒng","Traditional"],
  ["建筑","jiànzhù","Building / architecture"],
  ["文化","wénhuà","Culture"],
  ["浓","nóng","Strong / dense"],
  ["着急","zháojí","Anxious / in a hurry"],
  ["聊天","liáotiān","To chat"],
  ["繁华","fánhuá","Bustling / prosperous"],
  ["生活方式","shēnghuó fāngshì","Lifestyle"],
  ["年轻人","niánqīngrén","Young people"],
  ["忙","máng","Busy"],
  ["购物中心","gòuwù zhōngxīn","Shopping center"],
  ["电影院","diànyǐngyuàn","Cinema"],
  ["放松","fàngsōng","To relax"],
  ["自然","zìrán","Nature"],
  ["周末","zhōumò","Weekend"],
  ["爬山","páshān","To hike / climb a mountain"],
  ["瀑布","pùbù","Waterfall"],
  ["农场","nóngchǎng","Farm"],
  ["瑜伽","yújiā","Yoga"],
  ["冥想","míngxiǎng","Meditation"],
  ["课程","kèchéng","Course"],
  ["咖啡店","kāfēidiàn","Café"],
  ["艺术","yìshù","Art"],
  ["展览","zhǎnlǎn","Exhibition"],
  ["逛","guàng","To stroll / browse"],
  ["博物馆","bówùguǎn","Museum"],
  ["旁边","pángbiān","Beside / next to"],
  ["气息","qìxī","Atmosphere / vibe"],
  ["市中心","shìzhōngxīn","City center"],
  ["休假","xiūjià","Day off / to take leave"],
  ["文章","wénzhāng","Article"],
  ["适应","shìyìng","To adapt to"],
  ["环境","huánjìng","Environment"],
  ["容易","róngyì","Easy"],
  ["刚","gāng","Just (a moment ago)"],
  ["吵","chǎo","Noisy"],
  ["摩托车","mótuōchē","Motorcycle"],
  ["声音","shēngyīn","Sound / voice"],
  ["响","xiǎng","Loud"],
  ["挤","jǐ","To squeeze / crowded"],
  ["满","mǎn","Full"],
  ["累","lèi","Tired"],
  ["习惯","xíguàn","Habit / to get used to"],
  ["发现","fāxiàn","To discover"],
  ["方便","fāngbiàn","Convenient"],
  ["到处","dàochù","Everywhere"],
  ["便利店","biànlìdiàn","Convenience store"],
  ["餐厅","cāntīng","Restaurant"],
  ["出租车","chūzūchē","Taxi"],
  ["游客","yóukè","Tourist"],
  ["区域","qūyù","Area / district"],
  ["有意思","yǒu yìsi","Interesting"],
  ["选择","xuǎnzé","To choose / choice"],
  ["以后","yǐhòu","After / later"],
  ["商店","shāngdiàn","Shop"],
  ["关门","guānmén","To close (a shop)"],
  ["变","biàn","To change / become"],
  ["少","shǎo","Few / little"],
  ["感受","gǎnshòu","To feel / experience"],
  ["平静","píngjìng","Calm / peace"],
  ["好像","hǎoxiàng","To seem like"],
  ["适合","shìhé","To suit"],
  ["活泼","huópo","Lively / active"],
  ["认识","rènshi","To know / meet (someone)"],
  ["参加","cānjiā","To join / take part"],
  ["独处","dúchǔ","To be alone"],
  ["享受","xiǎngshòu","To enjoy"],
  ["空间","kōngjiān","Space"],
  ["看法","kànfǎ","View / opinion"],
  ["改变","gǎibiàn","To change"],
  ["开始","kāishǐ","To begin / start"],
  ["偏远","piānyuǎn","Remote"],
  ["久","jiǔ","Long (in time)"],
  ["精彩","jīngcǎi","Exciting / brilliant"],
  ["美丽","měilì","Beautiful"],
  ["重要","zhòngyào","Important"],
  ["事情","shìqing","Matter / thing"],
  ["无论","wúlùn","No matter"],
  ["身边","shēnbiān","At one's side"],
  ["通过","tōngguò","Through / by means of"],
  ["健身","jiànshēn","To work out / fitness"],
  ["语言","yǔyán","Language"],
  ["志愿者","zhìyuànzhě","Volunteer"],
  ["尝试","chángshì","To try / attempt"],
  ["打招呼","dǎ zhāohu","To greet / say hello"],
  ["当地","dāngdì","Local"],
  ["友好","yǒuhǎo","Friendly"],
  ["想家","xiǎngjiā","Homesick"],
  ["山","shān","Mountain"],
  ["森林","sēnlín","Forest"],
  ["帮助","bāngzhù","Help / to help"],
  ["幸福","xìngfú","Happiness / wellbeing"],
  ["吸引","xīyǐn","To attract"],
  ["旅居","lǚjū","To live abroad"],
  ["国外","guówài","Abroad / overseas"],
  ["购物","gòuwù","Shopping"],
  ["打折","dǎzhé","To give a discount"],
  ["试","shì","To try (on)"],
  ["试衣间","shìyījiān","Fitting room"],
  ["当然","dāngrán","Of course"],
  ["号","hào","Size"],
  ["便宜","piányi","Cheap"],
  ["贵","guì","Expensive"],
  ["多少钱","duōshao qián","How much (money)"],
  ["怎么样","zěnmeyàng","How about / how is it"],
  ["衣服","yīfu","Clothes"],
  ["裙子","qúnzi","Skirt / dress"],
  ["裤子","kùzi","Trousers"],
  ["衬衫","chènshān","Shirt"],
  ["鞋","xié","Shoes"],
  ["卖","mài","To sell"],
  ["支付","zhīfù","To pay"],
  ["信用卡","xìnyòngkǎ","Credit card"],
  ["礼物","lǐwù","Gift"],
  ["寄","jì","To mail / send"],
  ["明信片","míngxìnpiàn","Postcard"],
  ["纪念品","jìniànpǐn","Souvenir"],
  ["房子","fángzi","House"],
  ["租","zū","To rent"],
  ["租金","zūjīn","Rent (fee)"],
  ["中介","zhōngjiè","(Real estate) agent"],
  ["合适","héshì","Suitable"],
  ["位置","wèizhi","Location"],
  ["厨房","chúfáng","Kitchen"],
  ["卫生间","wèishēngjiān","Bathroom / toilet"],
  ["卧室","wòshì","Bedroom"],
  ["客厅","kètīng","Living room"],
  ["阳台","yángtái","Balcony"],
  ["家具","jiāju","Furniture"],
  ["电梯","diàntī","Elevator"],
  ["小区","xiǎoqū","Residential compound"],
  ["房东","fángdōng","Landlord"],
  ["朝南","cháonán","To face south"],
  ["因为","yīnwèi","Because"],
  ["所以","suǒyǐ","So / therefore"],
  ["要是","yàoshì","If"],
  ["搬","bān","To move (house)"],
  ["满意","mǎnyì","Satisfied"],
  ["宠物","chǒngwù","Pet"],
  ["天气","tiānqì","Weather"],
  ["季节","jìjié","Season"],
  ["春天","chūntiān","Spring"],
  ["夏天","xiàtiān","Summer"],
  ["秋天","qiūtiān","Autumn"],
  ["冬天","dōngtiān","Winter"],
  ["暖和","nuǎnhuo","Warm"],
  ["热","rè","Hot"],
  ["冷","lěng","Cold"],
  ["凉快","liángkuai","Cool"],
  ["晴","qíng","Sunny"],
  ["阴","yīn","Overcast"],
  ["多云","duōyún","Cloudy"],
  ["刮风","guāfēng","Windy"],
  ["下雨","xiàyǔ","To rain"],
  ["下雪","xiàxuě","To snow"],
  ["度","dù","Degree"],
  ["零下","língxià","Below zero"],
  ["天气预报","tiānqì yùbào","Weather forecast"],
  ["准","zhǔn","Accurate"],
  ["伞","sǎn","Umbrella"],
  ["雨季","yǔjì","Rainy season"],
  ["旱季","hànjì","Dry season"],
  ["南方","nánfāng","The south"],
  ["北方","běifāng","The north"],
  ["游泳","yóuyǒng","To swim"],
  ["滑雪","huáxuě","To ski"],
  ["野餐","yěcān","Picnic"],
  ["散步","sànbù","To take a walk"],
  ["生病","shēngbìng","To get sick"],
  ["感冒","gǎnmào","Cold / flu"],
  ["咳嗽","késou","To cough"],
  ["发烧","fāshāo","To have a fever"],
  ["打喷嚏","dǎ pēntì","To sneeze"],
  ["流鼻涕","liú bítì","Runny nose"],
  ["头疼","tóu téng","Headache"],
  ["嗓子疼","sǎngzi téng","Sore throat"],
  ["肚子疼","dùzi téng","Stomachache"],
  ["疼","téng","To hurt / ache"],
  ["药","yào","Medicine"],
  ["吃药","chī yào","To take medicine"],
  ["药店","yàodiàn","Pharmacy"],
  ["医院","yīyuàn","Hospital"],
  ["医生","yīshēng","Doctor"],
  ["过敏","guòmǐn","Allergic"],
  ["片","piàn","Tablet (measure word)"],
  ["次","cì","Time(s) (measure word)"],
  ["饭后","fàn hòu","After meals"],
  ["睡前","shuì qián","Before bed"],
  ["远程工作","yuǎnchéng gōngzuò","Remote work"],
  ["办公室","bàngōngshì","Office"],
  ["电脑","diànnǎo","Computer"],
  ["网络","wǎngluò","Internet"],
  ["同事","tóngshì","Colleague"],
  ["午饭","wǔfàn","Lunch"],
  ["孤独","gūdú","Lonely"],
  ["分心","fēnxīn","Distracted"],
  ["解决","jiějué","To solve"],
  ["安排","ānpái","To arrange"],
  ["方式","fāngshì","Way / method"],
  ["自由","zìyóu","Free / freedom"],
  ["困难","kùnnan","Difficulty"],
  ["体验","tǐyàn","To experience"],
  ["桌子","zhuōzi","Table / desk"],
  ["自由职业","zìyóu zhíyè","Freelance"],
  ["公司","gōngsī","Company"],
  ["老板","lǎobǎn","Boss"],
  ["客户","kèhù","Client"],
  ["压力","yālì","Stress / pressure"],
  ["担心","dānxīn","To worry"],
  ["假期","jiàqī","Holiday / vacation"],
  ["推迟","tuīchí","To postpone"],
  ["赚钱","zhuànqián","To make money"],
  ["越来越","yuèláiyuè","More and more"],
  ["主意","zhǔyi","Idea"],
  ["存款","cúnkuǎn","Savings"],
  ["认真","rènzhēn","Serious / seriously"],
  ["调查","diàochá","Survey"],
  ["约会","yuēhuì","Date"],
  ["爱好","àihào","Hobby"],
  ["感兴趣","gǎn xìngqù","To be interested in"],
  ["做饭","zuòfàn","To cook"],
  ["下棋","xiàqí","To play chess"],
  ["跳舞","tiàowǔ","To dance"],
  ["做运动","zuò yùndòng","To do exercise"],
  ["健身房","jiànshēnfáng","Gym"],
  ["打羽毛球","dǎ yǔmáoqiú","To play badminton"],
  ["攀岩","pānyán","Rock climbing"],
  ["射箭","shèjiàn","Archery"],
  ["摄影","shèyǐng","Photography"],
  ["音乐会","yīnyuèhuì","Concert"],
  ["编程","biānchéng","Programming"],
  ["老年人","lǎoniánrén","Elderly people"],
  ["相同","xiāngtóng","Same"],
  ["离","lí","(Distance) from"],
  ["近","jìn","Near"],
  ["远","yuǎn","Far"],
  ["公里","gōnglǐ","Kilometer"],
  ["换乘","huànchéng","To transfer (transit)"],
  ["一直","yìzhí","Straight / continuously"],
  ["飞机","fēijī","Airplane"],
  ["火车","huǒchē","Train"],
  ["高铁","gāotiě","High-speed rail"],
  ["船","chuán","Boat / ship"],
  ["公共汽车","gōnggòng qìchē","Bus"],
  ["开车","kāichē","To drive"],
  ["坐车","zuòchē","To ride (in a vehicle)"],
  ["驾照","jiàzhào","Driver's license"],
  ["安全帽","ānquánmào","Helmet"],
  ["送","sòng","To give / see off / deliver"],
  ["做菜","zuòcài","To cook (dishes)"],
  ["美食","měishí","Cuisine / good food"],
  ["火锅","huǒguō","Hotpot"],
  ["煮","zhǔ","To boil"],
  ["炒","chǎo","To stir-fry"],
  ["煎","jiān","To pan-fry"],
  ["蒸","zhēng","To steam"],
  ["烤","kǎo","To roast / grill"],
  ["锅","guō","Pot"],
  ["碗","wǎn","Bowl"],
  ["筷子","kuàizi","Chopsticks"],
  ["鱼","yú","Fish"],
  ["鸡蛋","jīdàn","Egg"],
  ["牛肉","niúròu","Beef"],
  ["酱油","jiàngyóu","Soy sauce"],
  ["盐","yán","Salt"],
  ["糖","táng","Sugar"],
  ["辣椒","làjiāo","Chili"],
  ["辣","là","Spicy"],
  ["甜","tián","Sweet"],
  ["酸","suān","Sour"],
  ["洋葱","yángcōng","Onion"],
  ["姜","jiāng","Ginger"],
  ["奶酪","nǎilào","Cheese"],
  ["虽然","suīrán","Although"],
  ["不过","búguò","However"],
  ["而且","érqiě","Moreover"],
  ["差不多","chàbùduō","Almost"],
  ["大概","dàgài","About / probably"],
  ["一般","yìbān","Usually / ordinary"],
  ["最近","zuìjìn","Recently"],
  ["然后","ránhòu","Then / afterwards"],
  ["一起","yìqǐ","Together"],
  ["可能","kěnéng","Maybe / possibly"],
  ["觉得","juéde","To feel / think"],
  ["需要","xūyào","To need"],
  ["决定","juédìng","To decide"],
  ["一点儿也不","yìdiǎnr yě bù","Not at all"],
  ["不得不","bùdébù","To have to"],
  ["大自然","dàzìrán","Nature"],
  ["接受","jiēshòu","To accept"],
  ["穿","chuān","To wear (clothes)"],
  ["戴","dài","To wear (accessories)"],
  ["背","bēi","To carry on the back"],
  ["帽子","màozi","Hat"],
  ["围巾","wéijīn","Scarf"],
  ["领带","lǐngdài","Necktie"],
  ["皮带","pídài","Belt"],
  ["项链","xiàngliàn","Necklace"],
  ["戒指","jièzhi","Ring"],
  ["耳环","ěrhuán","Earring"],
  ["手表","shǒubiǎo","Watch"],
  ["眼镜","yǎnjìng","Glasses"],
  ["袜子","wàzi","Socks"],
  ["外套","wàitào","Coat / jacket"],
  ["包","bāo","Bag"],
  ["袋子","dàizi","Bag / sack"],
  ["首饰","shǒushì","Jewelry"],
  ["打扮","dǎban","To dress up"],
  ["刀","dāo","Knife"],
  ["盘子","pánzi","Plate"],
  ["勺子","sháozi","Spoon"],
  ["微波炉","wēibōlú","Microwave"],
  ["烤箱","kǎoxiāng","Oven"],
  ["菜板","càibǎn","Cutting board"],
  ["虾","xiā","Shrimp"],
  ["醋","cù","Vinegar"],
  ["胡椒粉","hújiāofěn","Pepper (powder)"],
  ["蒜","suàn","Garlic"],
  ["白菜","báicài","Chinese cabbage"],
  ["香肠","xiāngcháng","Sausage"],
  ["拌","bàn","To mix / toss"],
  ["炖","dùn","To stew"],
  ["炸","zhá","To deep-fry"],
  ["清淡","qīngdàn","Light (in flavor)"],
  ["油腻","yóunì","Greasy"],
  ["调料","tiáoliào","Seasoning"],
  ["机票","jīpiào","Plane ticket"],
  ["火车站","huǒchēzhàn","Train station"],
  ["地铁站","dìtiězhàn","Subway station"],
  ["乘客","chéngkè","Passenger"],
  ["航班","hángbān","Flight"],
  ["头等舱","tóuděngcāng","First class"],
  ["经济舱","jīngjìcāng","Economy class"],
  ["登机","dēngjī","To board (a plane)"],
  ["私家车","sījiāchē","Private car"],
  ["长途汽车","chángtú qìchē","Long-distance coach"],
  ["始发站","shǐfāzhàn","Departure station"],
  ["终点站","zhōngdiǎnzhàn","Terminus / last stop"],
  ["往返","wǎngfǎn","Round-trip"],
  ["单程","dānchéng","One-way"],
  ["电动车","diàndòngchē","Electric scooter"],
  ["灯","dēng","Light / lamp"],
  ["窗户","chuānghu","Window"],
  ["空调","kōngtiáo","Air conditioner"],
  ["电视","diànshì","Television"],
  ["沙发","shāfā","Sofa"],
  ["床","chuáng","Bed"],
  ["椅子","yǐzi","Chair"],
  ["书柜","shūguì","Bookcase"],
  ["衣柜","yīguì","Wardrobe"],
  ["冰箱","bīngxiāng","Refrigerator"],
  ["电风扇","diànfēngshàn","Electric fan"],
  ["墙","qiáng","Wall"],
  ["地毯","dìtǎn","Carpet / rug"],
  ["窗帘","chuānglián","Curtain"],
  ["钟","zhōng","Clock"],
  ["挂","guà","To hang"],
  ["放","fàng","To put / place"],
  ["摆","bǎi","To place / arrange"],
  ["早睡早起","zǎoshuì zǎoqǐ","Early to bed, early to rise"],
  ["熬夜","áoyè","To stay up late"],
  ["夜猫子","yèmāozi","Night owl"],
  ["作息时间","zuòxī shíjiān","Daily schedule / routine"],
  ["按时","ànshí","On time"],
  ["口味清淡","kǒuwèi qīngdàn","Light taste / bland diet"],
  ["口味重","kǒuwèi zhòng","Strong / heavy taste"],
  ["八成饱","bāchéng bǎo","Eating until 80% full"],
  ["喝茶/咖啡","hē chá / hē kāfēi","To drink tea/coffee (as a habit)"],
  ["预习","yùxí","To preview / prestudy"],
  ["上课","shàngkè","To attend class"],
  ["做作业","zuò zuòyè","To do homework"],
  ["加班","jiābān","To work overtime"],
  ["素食主义","sùshí zhǔyì","Vegetarianism"],
  ["不是……而是……","bú shì……, ér shì……","It's not that..., but rather..."],
  ["着","zhe","(particle marking ongoing action/state)"],
  ["好起来","hǎo qǐlái","To start getting better"],
  ["带","dài","To bring / to lead / to carry"],
  ["看情况","kàn qíngkuàng","It depends / see how things go"],
  ["不好意思","bù hǎoyìsi","Embarrassed / excuse me"],
  ["记得","jìde","To remember"],
  ["迟到","chídào","To be late"],
  ["堵车","dǔchē","Traffic jam"],
  ["起床","qǐchuáng","To get up (from bed)"],
  ["又","yòu","Again"],
  ["跑步","pǎobù","To run / jog"],
  ["减肥","jiǎnféi","To diet / lose weight"],
  ["考试","kǎoshì","Exam / test"],
  ["普通人","pǔtōngrén","Ordinary person"],
  ["画家","huàjiā","Painter"],
  ["有名","yǒumíng","Famous / well-known"],
  ["对……来说","duì……láishuō","As far as ... is concerned"],
  ["家乡","jiāxiāng","Hometown"],
  ["市区","shìqū","Downtown / city center"],
  ["郊区","jiāoqū","Suburbs"],
  ["农村","nóngcūn","Countryside / village"],
  ["小镇","xiǎozhèn","Small town"],
  ["优点","yōudiǎn","Advantage"],
  ["缺点","quēdiǎn","Disadvantage"],
  ["机会","jīhuì","Opportunity / chance"],
  ["物价","wùjià","Prices (of goods)"],
  ["质量","zhìliàng","Quality"],
  ["工资","gōngzī","Salary / wage"],
  ["单纯","dānchún","Simple / pure (life)"],
  ["历史","lìshǐ","History"],
  ["商业中心","shāngyè zhōngxīn","Business center"],
  ["逛街","guàngjiē","To go shopping / stroll the streets"],
  ["高楼","gāolóu","Tall building / high-rise"],
  ["胡同","hútòng","Hutong / alley"],
  ["四合院","sìhéyuàn","Courtyard house"],
  ["长大","zhǎngdà","To grow up"],
  ["空气","kōngqì","Air"],
  ["新鲜","xīnxiān","Fresh"],
  ["高速公路","gāosù gōnglù","Highway / expressway"],
  ["花","huā","To spend (time/money)"],
  ["值得","zhídé","Worth it"],
  ["树","shù","Tree"],
  ["田野","tiányě","Field / farmland"],
  ["岛","dǎo","Island"],
  ["舒服","shūfu","Comfortable"],
  ["想念","xiǎngniàn","To miss (someone/something)"],
  ["记忆","jìyì","Memory"],
  ["珍贵","zhēnguì","Precious"],
  ["永远","yǒngyuǎn","Forever"],
  ["变化","biànhuà","Change"],
  ["熟悉","shúxī","Familiar"],
  ["风景","fēngjǐng","Scenery"],
  ["温暖","wēnnuǎn","Warm (feeling)"],
  ["入乡随俗","rù xiāng suí sú","When in Rome, do as the Romans do"],
  ["或许","huòxǔ","Perhaps / maybe"],
  ["潮湿","cháoshī","Humid / damp"],
  ["超市","chāoshì","Supermarket"],
  ["渐渐","jiànjiàn","Gradually / little by little"],
  ["比如","bǐrú","For example"],
  ["晚睡晚起","wǎn shuì wǎn qǐ","To sleep late and rise late"],
  ["进","jìn","To enter"],
  ["教室","jiàoshì","Classroom"],
  ["大家","dàjiā","Everyone"],
  ["为了","wèile","In order to"],
  ["买","mǎi","To buy"],
  ["闹钟","nàozhōng","Alarm clock"],
  ["懒虫","lǎnchóng","Lazybones"],
  ["该","gāi","Should"],
  ["尽管","jǐnguǎn","Although"],
  ["感谢","gǎnxiè","To thank / appreciate"],
  ["设置","shèzhì","To set (up)"],
  ["中午","zhōngwǔ","Noon"],
  ["时间","shíjiān","Time"],
  ["有些","yǒuxiē","Some"],
  ["见面","jiànmiàn","To meet (each other)"],
  ["问好","wènhǎo","To say hello"],
  ["奇怪","qíguài","Strange / weird"],
  ["问题","wèntí","Question / problem"],
  ["邻居","línjū","Neighbor"],
  ["对话","duìhuà","Dialogue / conversation"],
  ["外面","wàimiàn","Outside"],
  ["如果","rúguǒ","If"],
  ["跟","gēn","With (preposition)"],
  ["生气","shēngqì","Angry / to get mad"],
  ["可是","kěshì","But"],
  ["挺","tǐng","Quite / rather"],
  ["亲切","qīnqiè","Warm and friendly / cordial"],
  ["知道","zhīdào","To know"],
  ["关心","guānxīn","To care about"],
  ["回答","huídá","To answer / respond"],
  ["成语","chéngyǔ","Idiom"],
  ["意思","yìsi","Meaning"],
  ["地方","dìfang","Place"],
  ["风俗","fēngsú","Custom"],
  ["后悔","hòuhuǐ","To regret"],
  ["交朋友","jiāo péngyou","To make friends"],
  ["玩具","wánjù","Toy"],
  ["榴莲","liúlián","Durian"],
  ["食物","shíwù","Food"],
  ["当心","dāngxīn","Be careful / watch out"],
  ["缘分","yuánfèn","Fate that brings people together"],
  ["过程","guòchéng","Process"],
  ["谁","shéi","Who"],
  ["哪些","nǎxiē","Which (ones)"],
  ["方面","fāngmiàn","Aspect / area"],
  ["阅读","yuèdú","Reading / to read"],
  ["平时","píngshí","Usually / in normal times"],
  ["汉语","Hànyǔ","Chinese (language)"],
  ["中文","Zhōngwén","Chinese (language / writing)"],
  ["努力","nǔlì","To work hard / diligent"],
  ["首","shǒu","(measure word for songs)"],
  ["好好儿","hǎohāor","Properly / thoroughly"],
  ["再","zài","Again / then"],
  ["还","hái","Still / also"],
  ["唱","chàng","To sing"],
  ["歌","gē","Song"],
  ["旅行","lǚxíng","To travel"],
  ["小时候","xiǎoshíhou","Childhood / when young"],
  ["英语","Yīngyǔ","English (language)"],
  ["其实","qíshí","In fact / actually"],
  ["高兴","gāoxìng","Happy / glad"],
  ["难","nán","Difficult"],
  ["怕","pà","To be afraid of"],
  ["听说","tīngshuō","To hear that / they say"],
  ["那么","nàme","So / such"],
  ["告诉","gàosu","To tell"],
  ["提高","tígāo","To improve / raise"],
  ["能力","nénglì","Ability"],
  ["方法","fāngfǎ","Method"],
  ["这样","zhèyàng","Like this / this way"],
  ["有点儿","yǒudiǎnr","A little bit"],
  ["不用","búyòng","No need to"],
  ["岁","suì","Years old"],
  ["功夫","gōngfu","Kung fu"],
  ["不但……而且……","búdàn……, érqiě……","Not only..., but also..."],
  ["教","jiāo","To teach"],
  ["做人","zuòrén","To conduct oneself"],
  ["道理","dàoli","Principle / sense"],
  ["后来","hòulái","Later / afterwards"],
  ["没用","méiyòng","Useless"],
  ["挣钱","zhèngqián","To earn money"],
  ["出息","chūxi","Prospects / promise"],
  ["茶","chá","Tea"],
  ["菜","cài","Dish / food"],
  ["家人","jiārén","Family members"],
  ["找","zhǎo","To look for / find"],
  ["元素","yuánsù","Element"],
  ["书架","shūjià","Bookshelf"],
  ["唐装","tángzhuāng","Tang suit"],
  ["留学","liúxué","To study abroad"],
  ["学费","xuéfèi","Tuition"],
  ["打工","dǎgōng","To work a part-time job"],
  ["进步","jìnbù","To make progress"],
  ["快……了","kuài……le","About to / soon"],
  ["毕业","bìyè","To graduate"],
  ["用","yòng","To use"],
  ["当","dāng","To work as / to be (a profession)"],
  ["饭馆","fànguǎn","Restaurant (small)"],
  ["厨师","chúshī","Chef / cook"],
  ["宫保鸡丁","gōngbǎo jīdīng","Kung Pao chicken"],
  ["麻婆豆腐","mápó dòufu","Mapo tofu"],
  ["好吃","hǎochī","Delicious"],
  ["想起来","xiǎng qǐlái","To recall / think of"],
  ["流口水","liú kǒushuǐ","To drool"],
  ["导游","dǎoyóu","Tour guide"],
  ["不错","búcuò","Not bad / pretty good"],
  ["讨厌","tǎoyàn","To dislike / annoying"],
  ["咖啡师","kāfēishī","Barista"],
  ["自己","zìjǐ","Oneself"],
  ["想好","xiǎnghǎo","To decide / make up one's mind"],
  ["关系","guānxi","Relation / connection"],
  ["越……越……","yuè……yuè……","The more..., the more..."],
  ["懂","dǒng","To understand"],
  ["明白","míngbai","To understand / clear"],
  ["误解","wùjiě","To misunderstand"],
  ["表扬","biǎoyáng","To praise"],
  ["错","cuò","Wrong / mistake"],
  ["西瓜","xīguā","Watermelon"],
  ["下车","xiàchē","To get off (a vehicle)"],
  ["东西","dōngxi","Thing / stuff"],
  ["老师","lǎoshī","Teacher"],
  ["出门","chūmén","To go out"],
  ["有趣","yǒuqù","Interesting / fun"],
  ["雨","yǔ","Rain"],
  ["一……就……","yī……jiù……","As soon as..., then..."],
  ["先","xiān","First / beforehand"],
  ["上网","shàngwǎng","To go online"],
  ["打开","dǎkāi","To open"],
  ["电子邮箱","diànzǐ yóuxiāng","Email inbox"],
  ["电子邮件","diànzǐ yóujiàn","Email"],
  ["邮件","yóujiàn","Mail / email"],
  ["成了","chéng le","To become"],
  ["收到","shōudào","To receive"],
  ["极了","jí le","Extremely (after adjective)"],
  ["情况","qíngkuàng","Situation"],
  ["得","děi","Have to / must"],
  ["发","fā","To send"],
  ["微信","Wēixìn","WeChat"],
  ["消息","xiāoxi","Message / news"],
  ["放心","fàngxīn","To be at ease / not worry"],
  ["小孩子","xiǎoháizi","Small child / kid"],
  ["身体","shēntǐ","Body / health"],
  ["讲课","jiǎngkè","To lecture / teach a class"],
  ["听得懂","tīng de dǒng","Able to understand (by listening)"],
  ["吃得惯","chī de guàn","Used to eating (a food)"],
  ["话","huà","Words / speech"],
  ["可惜","kěxī","Unfortunately / it's a pity"],
  ["眼睛","yǎnjing","Eyes"],
  ["有空","yǒu kòng","To have free time"],
  ["常","cháng","Often"],
  ["祝","zhù","To wish"],
  ["手机","shǒujī","Mobile phone"],
  ["没电","méi diàn","Out of battery"],
  ["充电","chōngdiàn","To charge (a battery)"],
  ["充电器","chōngdiànqì","Charger"],
  ["第一次","dì yī cì","The first time"],
  ["拿到","nádào","To get / obtain"],
  ["护照","hùzhào","Passport"],
  ["条件","tiáojiàn","Condition / requirement"],
  ["希望","xīwàng","To hope / hope"],
  ["亲爱的","qīn'ài de","Dear"],
  ["您","nín","You (polite)"],
  ["每次","měi cì","Every time"],
  ["笑脸","xiàoliǎn","Smiling face"],
  ["闻","wén","To smell"],
  ["香味儿","xiāngwèir","Aroma / fragrance"],
  ["饭菜","fàncài","Food / meal (dishes)"],
  ["想","xiǎng","To miss / to think / to want"],
  ["许多","xǔduō","Many / a lot"],
  ["一切","yíqiè","Everything / all"],
  ["别","bié","Don't"],
  ["为","wèi","For (someone)"],
  ["学会","xuéhuì","To learn (and master)"],
  ["西红柿","xīhóngshì","Tomato"],
  ["西红柿炒鸡蛋","xīhóngshì chǎo jīdàn","Stir-fried tomato and egg"],
  ["室友","shìyǒu","Roommate"],
  ["打算","dǎsuàn","To plan / intend"],
  ["附近","fùjìn","Nearby / vicinity"],
  ["秘密","mìmì","Secret"],
  ["班","bān","Class (group of students)"],
  ["姑娘","gūniang","Girl / young woman"],
  ["又……又……","yòu……yòu……","Both... and..."],
  ["真的","zhēn de","Really / truly"],
  ["太……了","tài……le","Too... / so..."],
  ["健康","jiànkāng","Healthy / health"],
  ["其他","qítā","Other"],
  ["空心菜","kōngxīncài","Water spinach"],
  ["对不起","duìbuqǐ","Sorry"],
  ["咖啡馆","kāfēiguǎn","Café / coffee house"],
  ["出去","chūqù","To go out"]
];
