// Builds audio/list.tsv (every clip the app can ask for) and audio/manifest.js.
// Runs on macOS via:  osascript -l JavaScript audio/build-list.js <repo folder>
// The text keys below must match exactly what app.js passes to speak().
function run(argv){
  const root = argv[0];
  let read, write;
  if(typeof ObjC !== "undefined"){
    ObjC.import("Foundation");
    read  = p => $.NSString.stringWithContentsOfFileEncodingError(root+"/"+p, $.NSUTF8StringEncoding, null).js;
    write = (p, s) => $(s).writeToFileAtomicallyEncodingError(root+"/"+p, true, $.NSUTF8StringEncoding, null);
  } else {
    const fs = require("fs");
    read  = p => fs.readFileSync(root+"/"+p, "utf8");
    write = (p, s) => fs.writeFileSync(root+"/"+p, s);
  }
  const g = {};
  const src = ["words.js","examples-a.js","examples-b.js","lessons.js","meta.js","radicals.js","words-2.js"]
    .map(f=>read(f).replace(/^const /gm, "var ")).join("\n;\n");
  (new Function("g", src + "\n;g.WORDS=WORDS; g.EXAMPLES=EXAMPLES_A.concat(EXAMPLES_B); g.RADICALS=RADICALS;"))(g);

  // --- same text rules as app.js ---
  const zhChunks = t => t.split(/……|…|\/|\.\.\./).map(s=>s.trim()).filter(Boolean);
  const enText = s => s.replace(/\.\.\.|…/g," ").replace(/\//g," or ");
  const exZh = s => s.replace(/[…．]+/g," ");

  const keys = [], seen = {};
  const add = (lang, text) => { const k = lang+"|"+text; if(text && !seen[k]){ seen[k] = 1; keys.push([lang, text]); } };
  g.WORDS.forEach((w,i)=>{
    zhChunks(w[0]).forEach(c=>add("zh", c));
    add("en", enText(w[2]));
    const ex = g.EXAMPLES[i];
    if(ex){ add("zh", exZh(ex[0])); add("en", enText(ex[2])); }
  });
  g.RADICALS.forEach(r=>{
    zhChunks(r[0]).forEach(c=>add("zh", c));
    add("en", enText(r[2]));
    r[4].forEach(e=>{ add("zh", e[0]); add("en", enText(e[2])); });
  });

  // stable file names from a hash of the key, so re-running only records new clips
  const fnv = s => { let h = 0x811c9dc5; for(let i=0;i<s.length;i++){ h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; } return ("0000000"+h.toString(16)).slice(-8); };
  const files = {}, used = {}, lines = [];
  keys.forEach(([lang, text])=>{
    let name = lang + "-" + fnv(lang+"|"+text), n = 1;
    while(used[name]) name = lang + "-" + fnv(lang+"|"+text) + "-" + (++n);
    used[name] = 1;
    files[lang+"|"+text] = name + ".m4a";
    lines.push(name + ".m4a\t" + lang + "\t" + text.replace(/[\t\n]/g," "));
  });
  write("audio/list.tsv", lines.join("\n") + "\n");
  write("audio/manifest.js", "// Generated by audio/make-audio.sh — maps spoken text to recorded clips.\nvar AUDIO_MANIFEST = " +
    JSON.stringify({ v:1, base:"audio/clips/", count: lines.length, files }) + ";\n");
  return lines.length + " clips listed";
}
if(typeof ObjC === "undefined" && typeof process !== "undefined") console.log(run(process.argv.slice(2)));
